### ISSUE TITLE
REQ: new target based on c64 for the upcoming Commander X16

### ISSUE THREAD

**Issue by tschak909** [cc65/cc65#934] opened 2019-09-04 20:22 UTC
David Murray is working with a team of engineers to develop an extended Commodore 64 design, adding all sorts of nice little features.

https://www.facebook.com/groups/CommanderX16/

There is an emulator available, and there is development hardware being released out into the wild.

Hardware manual here: 
https://github.com/commanderx16/x16-docs/blob/master/Programmer's%20Reference%20Guide.md?fbclid=IwAR1-gdxWQiScF8akykB_gm8yFT-k_Nc9stj6j2-d4q39XwfX99EKfcdfqEM

It looks like binaries emitted by CC65 almost work, something fails in crt0.s, and it ejects back out to BASIC, though.

**Comment by tschak909** [comment] 2019-09-04 20:32
From the FB group:

> cc65 works already with the C64 target, but needs a little hack at the beginning, see my other posting for an example. Add just these lines to redefine the CC65 stack from $0xa800-0xaff:
> 
> *((uint8_t*) 0x02) = 0x00;
> *((uint8_t*) 0x03) = 0xb0;
> This should be a included in a proper x16 custom target and with all the other x16 features.
>

**Comment by msx80** [comment] 2019-09-07 11:26
I second this, being able to compile C for the commanderx16 would be awesome!

**Comment by 3vi1** [comment] 2019-09-15 14:52
I too intend to try to make some X16 (after I wrap up current projects).  Maybe we can put our heads together and get the proper configurations set up and submitted.  https://cc65.github.io/doc/customizing.html

**Comment by greg-king5** [comment] 2019-09-15 18:56
I have written enough of it to make a typical "Hello world!" program work in the emulator.

**Comment by hasenbanck** [comment] 2019-09-16 05:51
@greg-king5 Could we maybe open a branch somewhere to sync development efforts (I did a quick POC myself this weekend)? I don't think it would be wise to upstream the changes yet, since the X16 project hasn't even finished yet selecting the components.

I played with the idea to simply activate the CBM library for the X16 target and fix everything broken step by step, but after thinking about this matter further, I think it's best to write it's own set of libraries since it vastly different.

**Comment by msx80** [comment] 2019-09-16 09:56
@hasenbanck well done, i'll give it a try! We could also make a "x16.h" or something to include common x16 code like the VERA struct in demo.c

**Comment by hasenbanck** [comment] 2019-09-16 10:11
@msx80 I only copied the bare minimum from the C64 library, until the compilation was successfull. The ```asminc/x16.inc``` doesn't contain the proper memory addresses / peripherals yet and there is as of right now no ```include/x16.h``` (I guess we should also create a ```include/_vera.h``` as it seems that it's the convention in cc65).

I think I will write some test code myself in the next days to test each hardware component from C and test which parts need to be added (Especially if the CBM library is working at all).

**Comment by hasenbanck** [comment] 2019-09-17 14:58
It seems that @greg-king5 and I'm currently doings some double work. I would really like to focus efforts to make this new target. Since it seems that you greg have much more experience with the codebase, I would like to rebase my efforts of your branch.

**Comment by greg-king5** [comment] 2019-09-17 19:27
OK.  For those who haven't noticed it, my current work is at
https://github.com/greg-king5/cc65/tree/commander-x16.

It's targeted at [release 30 of the emulator](https://github.com/commanderx16/x16-emulator/releases); therefore, the VERA (video chip) stuff currently aims at revision `0.7`.

**Comment by greg-king5** [comment] 2019-09-25 15:12
I "bumped" the library code to work with x16-emu release 31 (so, VERA 0.8).

`stdio` programs work very well.  `conio` programs work fairly well.  But, I see a problem with `testcode/lib/joy-test.s` when a key is held down for awhile.  Sometimes, parts of the lines are printed too far to the right.  I don't know if it's caused by my library or by the emulator.

**Comment by tschak909** [comment] 2019-09-25 15:26
i'm going to attempt a platoterm bring-up this weekend.

**Comment by greg-king5** [comment] 2019-09-27 08:01
With commit 18afc7c7038280e2443c64e31cf2f0092a484004, we have a `cx16` target.  The computer's firmware was derived from the Commodore 64; therefore, I put that target into the `cbm` family.  You can `#include <cbm.h>` when you write C programs for the Commander X16.

**Comment by oliverschmidt** [comment] 2019-09-27 08:25
Thanks :-)

**Comment by tschak909** [comment] 2019-09-27 17:00
@greg-king5 yeah, this is awesome! :) This will be enough to do a platoterm bring-up (once I get the graphics bits worked out)

There is also still some discussion as to just WHAT will be possible to connect to the x16 for connectivity, but at least platoterm will be ready for when there is a viable connectivity solution :)

-Thom

**Comment by GithubPrankster** [comment] 2019-09-28 00:38
I've tested a hello world, but the text in the emu converts to lowercase everywhere. How do I convert back in C? (Also, if mixed mode can be done.)
![image](https://user-images.githubusercontent.com/33995085/65808986-0ef3f800-e16f-11e9-9282-50afe202b0fc.png)

**Comment by greg-king5** [comment] 2019-09-28 02:33
> I've tested a "hello world", but the text in the emu converts to lowercase everywhere. How do I convert back, in C? (Also, if mixed mode can be done.)

Are you asking about the two fonts
1. UPPER-case/graphics
2. lower-/UPPER-case?

cc65's start-up code switches to the second font (the average C program expects both UPPER-case and lower-case letters).  You can change to the other font by printing a `0x8E` character to the screen.

The simplest way is to `#include <cbm.h>`; and, call a Kernal function:
```c
cbm_k_bsout(0x8E);
```

If you print other text to the screen, then you can combine the above character with your other stuff:
```c
printf("\x8ehello world!\n");
```
(conio functions won't change the font.)

Normally, you can't mix those two fonts on the same screen.  (Fancy tricks are possible with VERA's two layers; but, the Kernal doesn't support them.)

**Comment by alytle** [comment] 2019-10-12 16:55
Looks like r33 added 128 sprites, but the cx16 target doesn't seem to work in that version because of the RAM bank changes. Anything we can do to make it work with this newest release? Or is it just too much of a moving target?

**Comment by greg-king5** [comment] 2019-10-12 20:18
cc65 has been updated for x16emu R33.  You need to update your Git repository or a package.

**Comment by 3vi1** [comment] 2019-10-12 22:05
DEMO.PRG still appears to crash the emulator, with cc65, x16-roms, x16-emu, and x16-demo all built from current source.  https://github.com/commanderx16/x16-demo/issues/51

**Comment by L-Bouzid** [comment] 2019-10-23 01:21
> With commit [18afc7c](https://github.com/cc65/cc65/commit/18afc7c7038280e2443c64e31cf2f0092a484004), we have a `cx16` target. The computer's firmware was derived from the Commodore 64; therefore, I put that target into the `cbm` family. You can `#include <cbm.h>` when you write C programs for the Commander X16.

good work Greg ...

**Comment by Frank-Buss** [comment] 2019-10-24 05:34
With the latest x16-rom from today, the demo program doesn't work. I guess it is a problem with the recent changes of the RAM locations for the ROM variables. Looks like waitvsync hangs, because the TIME location was changed.

**Comment by greg-king5** [comment] 2019-10-24 12:48
I added `vpeek()` and `vpoke()` functions to the library.  They give to C programs a more straight-forward, and faster, access to VERA's internal RAM and registers.

If you have been using your own version of `vpoke()` in your programs, then you must rename it; or, you must refactor your programs to use the library version.  The new prototype is different from what most people have been using in C and BASIC!
https://github.com/cc65/cc65/blob/9fa90e2265b0d54e3fd9e6ec0227821f6a09d9de/include/cx16.h#L190-L193

**Comment by mobluse** [comment] 2019-11-17 22:29
It might be easier to maintain https://github.com/cc65/cc65/blob/master/asminc/cx16.inc by using rom.sym.
 
You can get old rom.sys files from the [releases page](https://github.com/commanderx16/x16-emulator/releases) in the compiled releases e.g. x16emu_linux-r34.zip, and then compare with e.g. diff to the newly generated. One could generate a new cx16.inc using the latest rom.sym using a program if one somehow used similar names in cx16.inc as in rom.sym. The RAM addresses that the ROM uses are also in rom.sym.

**Comment by greg-king5** [comment] 2020-01-11 07:29
Commit b66f7272af4c566df6205f55296ac365ecbf8c73 updated the library to prerelease 36.

**Comment by bobbyjim** [comment] 2020-01-20 18:44
> cc65's start-up code switches to the second font (the average C program expects both UPPER-case and lower-case letters). You can change to the other font by printing a `0x8E` character to the screen.
> 
> The simplest way is to `#include <cbm.h>`; and, call a Kernal function:
> 
> ```c
> cbm_k_bsout(0x8E);
> ```
> 
> If you print other text to the screen, then you can combine the above character with your other stuff:
> 
> ```c
> printf("\x8ehello world!\n");
> ```


Is this documented?  I had to dig into this thread to find this out...

**Comment by mrdudz** [comment] 2020-01-20 18:49
> If you print other text to the screen, then you can combine the above character with your other stuff:

mmh sure? wouldnt the string be subject to ascii->petscii conversion in that case?

**Comment by bobbyjim** [comment] 2020-01-20 20:09
> > If you print other text to the screen, then you can combine the above character with your other stuff:
> 
> mmh sure? wouldnt the string be subject to ascii->petscii conversion in that case?

Nope, the embedded hex code works (as does cbm_k_bsout()).

**Comment by greg-king5** [comment] 2020-01-21 15:17
> > If you print other text to the screen, then you can combine the above character with your other stuff:
> 
> mmh, sure? Wouldn't the string be subject to ascii->petscii conversion, in that case?

Only some of the control codes are translated.  `"\r\n\f\b"`, for example.  (The documents don't list the ones that are translated.)

**Comment by greg-king5** [comment] 2020-01-21 15:40
I added `CH_FONT_LOWER` and `CH_FONT_UPPER` to `<cbm.h>`.

**Comment by bobbyjim** [comment] 2020-01-21 15:41
> I added `CH_FONT_LOWER` and `CH_FONT_UPPER` to `<cbm.h>`.

Very friendly!  Thank you!

**Comment by greg-king5** [comment] 2020-01-23 14:40
> I added `CH_FONT_LOWER` and `CH_FONT_UPPER` to `<cbm.h>`.

In ca65 Assembly (`"cx16.inc"`), the spellings are slightly different: `CH::FONT_LOWER` and `CH::FONT_UPPER`.

**Comment by greg-king5** [comment] 2020-07-15 21:38
Commit 4296cbaf82d47bfe1c9d9b100dcdf534601f018b added a TGI (graphics) driver, 320 dots across, 200 dots down, and 256 colors.

**Comment by mrdudz** [comment] 2022-02-12 19:19
@greg-king5 can we close this? we have cx16 support now, right?

**Closed** 2022-02-12 21:43 UTC
Labels: feature request, libs
