### ISSUE TITLE
Raster interrupts kill keyboard

### ISSUE THREAD

**Issue by spektro** [cc65/cc65#324] opened 2016-07-24 02:14 UTC
I have a program for Plus/4 which uses raster interrupts. The interrupt routine works fine (I can split the screen) and the main program runs also well. The problem is that the raster interrupts kill the keyboard. cgetc() function placed in the main program loop receives nothing when I press keys.

If I add an interrupt routine without enabling raster interrupts, I can read the keyboard in the main program.

**Comment by spiro-trikaliotis** [comment] 2016-07-24 08:49
Did you remember to call the original IRQ routine? On the C64, its $EA31. Otherwise, the keyboard handling routine will not be called, and you will not get any key presses.

You can also use $EA61 on the C64 in case you do not want to mess with the ticker timer.

**Comment by spektro** [comment] 2016-07-25 03:06
It doesn't seem to work. If I call Plus/4's original interrupt routine ($CE0E) at the end of my interrupt routine, just before returning IRQ_NOT_HANDLED, interrupts stop to work.

I though all I need to do (in my interrupt routine) is to request a new raster interrupt and return IRQ_NOT_HANDLED and the cc65's IRQ handler (which restores the zero page registers) do the rest.

**Comment by spiro-trikaliotis** [comment] 2016-07-25 19:56
Janne, I must admit that I did not look into the code before. Now, I see that the IRQ handler are created by some mechanism  called "interruptor", and I do not know anything about it.

My suggestion above relied on standard behaviour, I did not know about the interruptors.

You might have better chance that someone can help you if you could post some real code that does not work. Try to minimize it as much as possible, and I (or someone else) might be able to help you.

**Comment by spektro** [comment] 2016-07-30 21:55
OK, here is a test program. It can be used for testing the regular and raster interrupts.

Define ENABLE_RASTER_INT to enable raster interrupts. If it's not defined, regular interrupts will be used.

Define ENABLE_READ_KEYBOARD to enable cgetc() call. cgetc() is the one which hangs when the raster interrupts are enabled.

A  character at the top left corner of the screen will show if the main program is running or not: the character will change when you press a key or it will change constantly if the keyboard reading is not enabled.

> #include <6502.h>
> #include <plus4.h>
> #include <peekpoke.h>
> #include <conio.h>
> 
> #define TEMP_STACK_SIZE 2048
> 
> /* Raster lines */
> #define RASTER_LINE_1 0x0137
> #define RASTER_LINE_2 0x009e
> 
> /* Macro for setting raster line */
> #define m_SetRasterline( RASTERLINE ) TED.imr = ( TED.imr & 0xfe ) | ( ( RASTERLINE & 0x0100 ) >> 8 ); TED.irq_rasterline = ( unsigned char ) ( RASTERLINE & 0x00ff )
> /* Macro for waiting rastern column */
> #define m_WaitRasterColumn( RASTERCOLUMN ) while ( TED.rastercolumn == RASTERCOLUMN ) {}
> 
> /* Define ENABLE_RASTER_INT to enable raster interrupts */
> #define ENABLE_RASTER_INT 1
> 
> /* Define ENABLE_READ_KEYBOARD to read user input */
> /*#define ENABLE_READ_KEYBOARD 1*/
> 
> void main ( void );
> void f_WaitRasterline ( unsigned int unRasterline );
> unsigned char f_IntRoutine ( void );
> unsigned char f_RastIntRoutine ( void );
> 
> unsigned char aucTempStack [ TEMP_STACK_SIZE ];
> 
> /*
> ** ff09 = TED.irr
> ** ff0a = TED.imr
> ** ff0b = TED.irq_rasterline
> */
> void main ( void ) {
>     unsigned char ucCount = 0;
> 
>     SEI ();
>     set_irq (
>         #ifdef ENABLE_RASTER_INT
>              &f_RastIntRoutine,
>         #else
>             &f_IntRoutine,
>         #endif
>         aucTempStack, TEMP_STACK_SIZE
>     );
> 
> 
>     #ifdef ENABLE_RASTER_INT
>         /* Enable raster interrupts */
>         TED.imr = TED.imr | 0x02;
> 
>         /* Set raster line (9 bits) */
>         m_SetRasterline ( RASTER_LINE_1 );
>     #endif
> 
>     CLI ();
> 
>     /* Print key presses */
>     for ( ;; ) {
>         /* Show that the main program is alive */
>         POKE ( 0x0c00, ucCount );
>         ++ucCount;
> 
>         /*
>         ** Read the keyboard and print the read character
>         ** If you enable keyboard reading while the raster interrupts
>         ** are running, the main program will halt to cgetc call .
>         */
>         #ifdef ENABLE_READ_KEYBOARD
>             cputc ( cgetc () );
>         #endif
>     }
> }
> 
> void f_WaitRasterline ( unsigned int unRasterline ) {
>     unsigned char ucMsb = ( unsigned char ) ( ( unRasterline & 0x0100 ) >> 8 );
>     unsigned char ucLsb = ( unsigned char ) ( unRasterline & 0x00ff );
>     while ( TED.rasterline_hi == ucMsb ) {}
>     while ( TED.rasterline_lo == ucLsb ) {}
> }
> 
> unsigned char f_IntRoutine ( void ) {
>     ++TED.bordercolor;
>     return ( IRQ_NOT_HANDLED );
> }
> 
> unsigned char f_RastIntRoutine ( void ) {
>     unsigned int unRasterline;
> 
>     /* Request new interrupt */
>     TED.irr = TED.irr;
> 
>     /* Get rasterline */
>     unRasterline = TED.imr & 0x01;
>     unRasterline = ( unRasterline << 8 ) | TED.irq_rasterline;
> 
>     /* Which raster line? */
>     switch ( unRasterline ) {
>         case RASTER_LINE_1: {
>             /* Set colors */
>             m_WaitRasterColumn ( 0x00 );
>             TED.bordercolor = BCOLOR_BLUE | CATTR_LUMA3;
>             TED.bgcolor     = BCOLOR_BLUE | CATTR_LUMA3;
> 
>             /* Request raster line 2 */
>             m_SetRasterline ( RASTER_LINE_2 );
> 
>             break;
>         }
>         case RASTER_LINE_2: {
>             /* Set colors */
>             m_WaitRasterColumn ( 0x00 );
>             TED.bordercolor = BCOLOR_GREEN | CATTR_LUMA3;
>             TED.bgcolor     = BCOLOR_GREEN | CATTR_LUMA3;
> 
>             /* Request raster line 1 */
>             m_SetRasterline ( RASTER_LINE_1 );
>             break;
>         }
>         default: {}
>     }
> 
>     return ( IRQ_NOT_HANDLED );
> }
>

**Comment by oliverschmidt** [comment] 2016-07-31 07:14
Hi,

> SEI ();
>
> set_irq( [...]
>
> I don't know enough about CBM raster interrupts to say what might be wrong
here but two more general remarks:

- Interrupt handlers set with set_irq come with quite some overhead
executed every time before the actual code is executed.
>
>
- set_irq does its own sei/cli. So your SEI needs to be below set_irq in
order to have an effect.

Regards,
Oliver

**Comment by spektro** [comment] 2016-08-05 05:37
Hi Oliver,
Yes, I've noticed that the interrupts slow down computer quite a bit. It's a shame really. I guess there is no way to make the cc65's interrupt stub faster and simpler.

> - set_irq does its own sei/cli. So your SEI needs to be below set_irq in order to have an effect.

Ah, that's good to know.

I changed the code like this, but it didn't help - **cgetc** still cannot read the keyboard.

```
    SEI ();
    #ifdef ENABLE_RASTER_INT
        /* Enable raster interrupts */
        TED.imr = TED.imr | 0x02;

        /* Set raster line (9 bits) */
        m_SetRasterline ( RASTER_LINE_1 );
    #endif

    set_irq (
        #ifdef ENABLE_RASTER_INT
             &f_RastIntRoutine,
        #else
            &f_IntRoutine,
        #endif
        aucTempStack, TEMP_STACK_SIZE
    );
    CLI ();
```

**Comment by greg-king5** [comment] 2016-08-05 16:38
If you change the first line in `f_IntRoutine()`, then you can see what the problem is (don't define ENABLE_RASTER_INT).
```C
#include <6502.h>
#include <plus4.h>
#include <peekpoke.h>
#include <conio.h>

#define TEMP_STACK_SIZE 1024

/* Raster lines */
#define RASTER_LINE_1 0x0137
#define RASTER_LINE_2 0x009e

/* Macro for setting raster line */
#define m_SetRasterline( RASTERLINE ) TED.imr = ( TED.imr & 0xfe ) | ( ( RASTERLINE & 0x0100 ) >> 8 ); TED.irq_rasterline = ( unsigned char ) ( RASTERLINE & 0x00ff )
/* Macro for waiting past raster column */
#define m_WaitRasterColumn( RASTERCOLUMN ) while ( TED.rastercolumn == RASTERCOLUMN ) {}

/* Define ENABLE_RASTER_INT to enable raster interrupts */
// #define ENABLE_RASTER_INT

/* Define ENABLE_READ_KEYBOARD to read user input */
#define ENABLE_READ_KEYBOARD

void f_WaitRasterline ( unsigned int unRasterline );
unsigned char f_IntRoutine ( void );
unsigned char f_RastIntRoutine ( void );

unsigned char aucTempStack [ TEMP_STACK_SIZE ];

/*
** ff09 = TED.irr
** ff0a = TED.imr
** ff0b = TED.irq_rasterline
*/
void main ( void ) {
    unsigned char ucCount = 0;

    set_irq (
#ifdef ENABLE_RASTER_INT
             f_RastIntRoutine,
#else
             f_IntRoutine,
#endif
             aucTempStack, TEMP_STACK_SIZE );

#ifdef ENABLE_RASTER_INT
    SEI ();
    /* Enable raster interrupts */
    TED.imr = TED.imr | 0x02;
    /* Set raster line (9 bits) */
    m_SetRasterline ( RASTER_LINE_1 );
    CLI ();
#endif

    /* Print key presses */
    for ( ;; ) {
        /* Show that the main program is alive */
        POKE ( 0x0c00, ++ucCount );

#ifdef ENABLE_READ_KEYBOARD
        /*
        ** Read the keyboard; and, print the read character.
        ** If you enable keyboard reading while the raster interrupts
        ** are running, the main program will halt in cgetc() call .
        */
        cputc ( cgetc () );
#endif
    }
}

void f_WaitRasterline ( unsigned int unRasterline ) {
    unsigned char ucMsb = ( unsigned char ) ( ( unRasterline & 0x0100 ) >> 8 );
    unsigned char ucLsb = ( unsigned char ) ( unRasterline & 0x00ff );
    while ( TED.rasterline_hi == ucMsb ) {}
    while ( TED.rasterline_lo == ucLsb ) {}
}

unsigned char f_IntRoutine ( void ) {
    TED.bordercolor ^= 0x01;
    return ( IRQ_NOT_HANDLED );
}

unsigned char f_RastIntRoutine ( void ) {
    unsigned int unRasterline;

    /* Request new raster interrupt  -- don't stop other interrupts! */
    TED.irr = 0x02;

    /* Get rasterline */
    unRasterline = TED.imr & 0x01;
    unRasterline = ( unRasterline << 8 ) | TED.irq_rasterline;

    /* Which raster line? */
    switch ( unRasterline ) {
        case RASTER_LINE_1: {
            /* Set colors */
            m_WaitRasterColumn ( 0x00 );
            TED.bordercolor = BCOLOR_BLUE | CATTR_LUMA3;
            TED.bgcolor     = BCOLOR_BLUE | CATTR_LUMA3;

            /* Request raster line 2 */
            m_SetRasterline ( RASTER_LINE_2 );
            break;
        }
        case RASTER_LINE_2: {
            /* Set colors */
            m_WaitRasterColumn ( 0x00 );
            TED.bordercolor = BCOLOR_GREEN | CATTR_LUMA3;
            TED.bgcolor     = BCOLOR_GREEN | CATTR_LUMA3;

            /* Request raster line 1 */
            m_SetRasterline ( RASTER_LINE_1 );
            break;
        }
        default: {}
    }
    return ( IRQ_HANDLED );
}
```

Commodore's TED computer models use raster interrupts to "drive" the Jiffy clock and the keyboard scanner.  If a program uses rasters, then it interferes with the Kernal.  If that program doesn't "eat" the interrupts, then the Kernal interferes with the program.  Therefore, your interrupt code will need to call the Kernal's `UDTIM` and `SCNKEY` routines one time during each video frame.

However, cc65 code needs to turn the ROM on and off.  Therefore, we will need to write special functions for the `plus4` library.

**Comment by oliverschmidt** [comment] 2016-08-05 21:24
@greg-king5: Thanks for your analysis.

Given what you write regarding memory banking I suppose it's appropriate to flag this issue as bug.

**Comment by greg-king5** [comment] 2016-08-05 23:05
Enhancement.  I must add two functions to the CBM library: `cbm_k_udtim()` and `cbm_k_scnkey()`.  On most of the platforms, the Assembly code simply will point to the Kernal's jump table.  But, the C16 and Plus4 libraries will need "trampolines" also; they will turn the ROM on, use it, then turn it off (normally, the run-time environment exposes as much RAM as possible).

**Comment by spektro** [comment] 2016-08-09 10:22
Thanks Greg!

**Comment by greg-king5** [comment] 2016-08-12 08:35
```C
    /* Request new raster interrupt  -- don't stop other interrupts! */
    TED.irr = 0x02;
```
Note to Oliver:  The above line prevents the Kernal from seeing raster interrupts -- so, the Kernal won't interfere.

```C
        case RASTER_LINE_2: {
            /* Set colors */
            m_WaitRasterColumn ( 0x00 );
            TED.bordercolor = BCOLOR_GREEN | CATTR_LUMA3;
            TED.bgcolor     = BCOLOR_GREEN | CATTR_LUMA3;

            /* Request raster line 1 */
            m_SetRasterline ( RASTER_LINE_1 );

            /* This program completely controls raster interrupts.  Therefore,
            ** the Plus4 Kernal won't run some vital functions.  The program
            ** must do it -- once during each video field.
            */
            cbm_k_scnkey ();    /* scan the keyboard matrix */
            cbm_k_udtim ();     /* "bump" the clock() value */
            break;
        }
```

- If your program uses _any_ keyboard input functions, then it needs to call `cbm_k_scnkey()`.
- If your program uses `clock()`, then it needs to call `cbm_k_udtim()`.

**Comment by oliverschmidt** [comment] 2016-08-21 13:11
Fixed with https://github.com/cc65/cc65/pull/332.

**Closed by oliverschmidt** 2016-08-21 13:11 UTC
Labels: enhancement
