### ISSUE TITLE
Performance regression of generated code in comparison to cc65 v2.13.3

### ISSUE THREAD

**Issue by vrubleg** [cc65/cc65#781] opened 2018-10-18 19:49 UTC
There are [dozens](http://nintendoage.com/forum/messageview.cfm?catid=22&threadid=169311&StartRow=1) of NES games which are written using cc65. But they still often use cc65 v2.13.3 because newer compiler generates slower code, and sometimes it is crucial. Time between frames is very limited, and if the code is not fast enough, the game will become twice slower.

Shiru provided me “Sir Ababol” from Mojon Twins as an example of a game which encountered the issue and had to be built using cc65 v2.13.3 to work properly. It is not the only example. I also was playing with cc65 and also encountered the same issue years ago, when cc65 was v2.14. I had even written about it to the mailing list then ([here](https://sourceforge.net/p/cc65/mailman/message/31568187/), I was a newbie in this area in 2013, so my explanation wasn't good enough). The issue wasn't resolved, so I decided to stick to cc65 v2.13.3 as others do.

Today I have tried to check if cc65 v2.17 generates at least as fast code as v2.13.3... And still no success.

Comparison of assembly listings reveals the reason (v2.17 on the left, v2.13.3 on the right):
![diff](http://veg.by/z/2018-10-18-22-41-14-fadc9770.png)

It generates calls to slow external subroutines instead of fast inline instructions. For example, `jsr pushax`: 50 cycles instead of 8. And it is inside of a loop. Of course it is slow. `-Oi` and other optimization flags don't help.

The demo to play with: http://veg.by/temp/cc65-regression.zip

**Comment by mrdudz** [comment] 2018-10-18 21:01
i'm not sure if this is really a regression - eg for what i do with cc65, optimizing for size is much more important than speed. no idea how to fix this though :)

**Comment by mrdudz** [comment] 2018-10-18 21:38
in my programs the performance critical things are written in assembler, and the parts written in C i want to be short :)

but indeed, different options to optimize for speed vs size would be nice.

**Comment by Fabrizio-Caruso** [comment] 2018-10-18 21:42
@vrubleg I spend hours on my code just to save a few bytes.
Compact size on 8 bit system is important. In my use-cases compact size is more important than speed. The Vic 20 has 5k of ram.
Having an option to choose size vs speed is a good idea.

**Comment by greg-king5** [comment] 2018-10-19 14:28
The optimizer option `-O` aims for size, while `-Oris` aims for speed.

**Comment by oliverschmidt** [comment] 2018-10-19 15:46
> The optimizer option -O aims for size, while -Oris aims for speed.

Exactly! I was actually surprised that this isn't known to about every cc65 user. So maybe it makes sense to additionally cite the cc65 doc here saying: 

`-Oi` is an alias for `-O --codesize 200`.

So you can (try to) customize the optimizer output further.

**Comment by Fabrizio-Caruso** [comment] 2018-10-19 15:49
@greg-king5 -Or produces more compact case than -O at least in my use-cases (register used in parameters of variables used at least 3 times)

**Comment by mrdudz** [comment] 2018-10-19 15:54
-Or is actually quite a sensible option... in many cases the code will get worse, not better :)

**Comment by oliverschmidt** [comment] 2018-10-19 15:54
Generally I wouldn't dare to try to assess if there are more users/projects struggling with cc65 generating too slow code or too large code. My personal projects tend to become too large, not too slow.

But coming back to this issue: Given that we already have `-O` vs. `-Oi` we can easily ask `-Oi` to generate larger but faster code. From that perspective there's no good reason why cc65 changed its behavior. And as such I follow the idea to classify this issue as a performance regression.

However, doing that is easy. Finding/fixing the issue is (supposed to be) hard ;-)

**Comment by Fabrizio-Caruso** [comment] 2018-10-19 15:59
@mrdudz yes if you use it blindly. 
From my personal experience I can say that if you use the register keyword on pointer parameters that are referenced at least 3 times, you will get smaller code consinstenly.
My goal is reducing code size at almost any cost so I used it and tried it in each single function.

**Comment by oliverschmidt** [comment] 2018-10-19 16:02
> My goal is reducing code size at almost any cost. So I used it and tried it in each single function and I got positive results in all the these cases.

Been there, done that ;-)

**Comment by mrdudz** [comment] 2018-10-19 16:06
yep its what i do as well :)

i still find it confusing that -Os isnt "optimize for size" though =)

**Comment by vrubleg** [comment] 2018-10-19 16:13
Yeah, but none of the options affect the things I'm talking about. It was changed in 2.14 and it affects all modes independently on options.

It would be good to find exact revision when the change was introduced. Probably, somebody have an idea of the exact reason of the changes? It will make much easier finding the revision.

I believe that the default mode should be the "balanced" one. You can ask the compiler for optimization for speed or for size, but by default it should be something most reasonable. And saving a byte with price of 42 cycles is not reasonable.

**Comment by mrdudz** [comment] 2018-10-19 16:19
> saving a byte with price of 42 cycles is not reasonable.
i think the core problem here is that speed critical parts aren't written in assembler :)

**Comment by vrubleg** [comment] 2018-10-19 16:28
@mrdudz, so, your suggestion is to use assembly for everything? =) In a game all the game logic is critical. There are games where all the game logic is written using cc65 (and ca65 is used for low level stuff), and they work nice.

**Comment by oliverschmidt** [comment] 2018-10-19 16:34
I'd prefer to not have a C vs. Asm discussion here. cc65 has optimizations clearly targeting to speed up the code even when it becomes larger. They are there and something seems to got broken about them. No point in discussing if they make sense nor if using them makes sense.

**Comment by mrdudz** [comment] 2018-10-19 16:36
@vrubleg: no and no.

and what oliver said. you could start binsearching for when it broke, i am sure gregg will then jump on it :)

**Comment by vrubleg** [comment] 2018-10-19 17:10
I've built [the last revision from Uz](https://github.com/cc65/cc65/tree/e6aa00b339e1f36ef6e05aa2238096c81307e779). It reports itself as v2.13.9, but it wasn't ever released. Actually, I was surprised how many commits were done by Uz after v2.13.3, I thought that he decided to leave the project right after v2.13.3.

The issue is already here. So it was introduced between v2.13.3 and v2.13.9.

**Comment by vrubleg** [comment] 2018-10-19 18:44
I have updated the archive: http://veg.by/files/temp/cc65-regression.zip
`cc65_old.exe` is revision `5f0db62f5825e19582fb9e51452c3eac96c80121`
`cc65_new.exe` is revision `e50649af2cdd3fcee258882db7986da68be03a2b`

**Comment by oliverschmidt** [comment] 2020-06-22 21:35
Fixed with https://github.com/cc65/cc65/pull/1053.

**Closed by oliverschmidt** 2020-06-22 21:35 UTC
Labels: bug

**Comment by vrubleg** [comment] 2020-06-22 22:24
Just tested it. Now cc65 generates code equal to cc65 v2.13.3, the difference is in numbers in label names only. (I'm a bit curious, why?)

**Comment by oliverschmidt** [comment] 2020-06-23 08:41
> Just tested it. Now cc65 generates code equal to cc65 v2.13.3

Thanks for testing - and the positive feedback :-)
