### ISSUE TITLE
[lib?] printf/scanf format specification for targets with translated charset?

### ISSUE THREAD

**Issue by acqn** [cc65/cc65#2400] opened 2024-02-02 15:53 UTC
This is something that I am unfamiliar with. When I was experimenting a format specification checker for the `printf` family, everything worked as expected until it came to the c16/c64/c128 targets - the letters used in normal format specifications are charmapped to something else and the checks failed. Of course, the `printf` output failed as well.

```c
#include <stdio.h>

int main(void)
{
    printf("This FAILED: %s", "ERROR");
}
```

Compiler (with the experimental format specification cheker) output with `-t c64`:
```
test.c:5: Warning: Invalid format specifier '? in 'printf'
test.c:5: Warning: Arguments unused by format string
```

Output with `sim65` is some garbage since the format specifier `%s` is translated to something else.

So the questions:
- Are the `printf`/`scanf` family functions supposed to "work" like this for these targets?
- How should a format specification checker work for these targets?

**Comment by mrdudz** [comment] 2024-02-02 16:15
If i understood correctly, your checker should simply translate the strings it checks against to the target character set before comparing them. 

So what happens is simply that all strings (and character literals) are translated into the target character set. Stuff like printf keeps working as expected, because in their implementation the same thing happens.

I am surprised about the error output though - since "%s" in petscii would turn out as "%S" if decoded as ascii - so perhaps you are applying the conversion the wrong way around?

(printf checker sounds super awesome. would be even more awesome if it could be used with arbitrary functions using pragmas or attributes, like gcc/clang can do)

**Comment by mrdudz** [comment] 2024-02-02 16:16
> If i understood correctly, your checker should simply translate the strings it checks against to the target character set before comparing them.

PS: this probably should use the currently active table(s) - since they can be changed using CHARMAP pragmas

**Comment by acqn** [comment] 2024-02-02 17:34
Oh I see. Thanks for the explanation. The error in the OP could be that I linked the code with `-t sim6502`. :p

**Comment by mrdudz** [comment] 2024-02-02 18:40
Oh yes, when you combine stuff assembled/compiled for different targets, all kind of strange things will happen :)

**Comment by sintech** [comment] 2024-09-06 21:11
I stumbled upon this while trying to implement new target with very different charset, where "%" is mapped to another char.
Doesn't it makes sense to translate charset only during last stage of console output to avoid such an issues with printf?

**Comment by mrdudz** [comment] 2024-09-06 21:17
No, that doesn't work. The translation must be applied to all string and character literals, at compile time. "console output" is not even related to this.

**Comment by sidneycadot** [comment] 2024-12-29 22:58
@sintech

Can I ask, what target are you implementing that has a character set that cannot represent a '%' ?

The C standards (at least since C99, but possibly earlier) require that a bunch of characters are represented in the execution character set (more informally known as the target character set). Among those characters is the '%' character. So I'm afraid your target cannot be expected to provide a compliant execution environment for C programs.

**Comment by sidneycadot** [comment] 2024-12-30 09:39
The fact that it is not in its usual place should not be a problem, per se: it is representable as 0xa5. The only required character by C99 that doesn't seem to be available is the tilde (~), but character 0x5e could work for that.

In principle it should be possible to support such a target. However, the problem you run into is that the printf format string parser (like the scanf format string parser) is written in 6502 assembly (the printf parser is in libsrc/common/_printf.s), and the ca65 assembler currently does not handle target-specific character translation. It effectively translates character constants like '%' to their ASCII values.

A somewhat similar issue was encountered a short while ago, concerning the fact that character constants in the assembler don't handle escape characters like '\n'.

In effect, ca65 does not properly handle target-specific character translation, assuming that that was taken care of by the C compiler. But this immediately clashes with the fact that some functionality (like printf format string parsing) is implemented directly in assembly.

While fixing this is certainly possible, it would be quite an undertaking.

I propose to make a new issue pinpointing the root cause of this problem in the assembler; and this issue could be closed, but still referred to in the new issue. Would that be okay with you?

**Comment by sintech** [comment] 2024-12-30 09:51
> I propose to make a new issue pinpointing the root cause of this problem in the assembler; and this issue could be closed, but still referred to in the new issue. Would you agree with that course of action?

Sure, thank you for the root cause explanation. I will create new issue.

**Comment by sidneycadot** [comment] 2024-12-30 12:41
Root cause issue reported in #2581. Closing this issue.

**Closed by sidneycadot** 2024-12-30 12:41 UTC
Labels: cc65

**Comment by GorillaSapiens** [comment] 2025-05-06 03:23
see comments related to this in #2642
