### ISSUE TITLE
Existing label not detected. C64 platform.

### ISSUE THREAD

**Issue by sblendorio** [cc65/cc65#1415] opened 2021-03-02 13:51 UTC
This code should work, but it works ONLY _un-commenting_ the **goto loop**:

    #include <c64.h>
    #include <stdio.h>
    
    void set_interrupt(void);
    void loop(void);
    
    void main(void) {
        set_interrupt();
        printf("Hello\n");
    }
    
    void set_interrupt(void) {
        asm("sei");
        asm("ldx #<%g", loop);
        asm("ldy #>%g", loop);
        asm("stx $0314");
        asm("sty $0315");
        asm("cli");
        asm("rts");
        // goto loop;
    loop: 
        asm("inc $d021");
        asm("jmp $ea31");
    }

infact this is the compiling result:

    $ cl65 -t c64 mouse.c -o mouse.prg
    Unresolved external 'L000F' referenced in:
      mouse.s(34)
      mouse.s(35)
    ld65: Error: 1 unresolved external(s) found - cannot create output file

un-commenting the **goto loop**, it works.

The issue is that the loop label is used in the asm instructions, but it's not detected.

**Comment by groessler** [comment] 2021-03-02 14:18
Sigh. Why are people insisting in using the inline assembler when it could be done the same with a standalone asm source file?
Sorry, I'm just musing, and I don't know why that happens.

**Comment by oliverschmidt** [comment] 2021-03-02 17:10
Duplicate of https://github.com/cc65/cc65/issues/897

**Closed by oliverschmidt** 2021-03-02 17:10 UTC
