### ISSUE TITLE
equality comparison is evaluated wrong in some cases

### ISSUE THREAD

**Issue by mrdudz** [cc65/cc65#167] opened 2015-07-03 01:53 UTC
Here is an example that demonstrates the behaviour:

``` c
    #include <stdio.h>
    #include <stdint.h>

    int main ( void)
    {
      uint8_t  joy_state = 0x7e;
      printf("bad: %u\n", 0 == (joy_state & 1) );
      printf("good: %u\n", (joy_state & 1) == 0 );

      return 0;
    }
```

This results in:

```
bad: 0
good: 1
```

http://www.cc65.org/mailarchive/2014-10/11680.html

**Comment by cacciatc** [comment] 2016-08-22 21:31
I am unable to reproduce this issue when building from HEAD. The output for the same source is now:

```
bad: 1
good: 1
```

**Comment by mrdudz** [comment] 2016-08-23 08:23
have you tried with all different combinations of optimization options? (a lot of times the bugs are in the optimizer)

**Comment by oliverschmidt** [comment] 2016-08-23 09:46
@cacciatc: Thanks for investigating :-)

@mrdudz: It would be beneficial if the optimization option(s) used for the demonstration would be included in the issue report in the first place ;-)

**Comment by cacciatc** [comment] 2016-08-23 14:41
Thanks for clarifying. Yep, I can reproduce it with the optimizer:

```
$ cat val/atest.c
#include <stdio.h>
#include <stdint.h>

int main ( void)
{
      uint8_t  joy_state = 0x7e;
      printf("bad: %u\n", 0 == (joy_state & 1) );
      printf("good: %u\n", (joy_state & 1) == 0 );

      return 0;
}
$ ../bin/cl65 -O -t sim6502 val/atest.c
$ ../bin/sim65 val/atest
bad: 0
good: 1
```

**Comment by mrdudz** [comment] 2016-08-23 17:01
> @mrdudz: It would be beneficial if the optimization option(s) used for the demonstration would be included in the issue report in the first place ;-)

i agree - but the original report didnt include that info either...

**Comment by cacciatc** [comment] 2016-08-26 02:32
After some more investigation it looks like OptStackOps may have something to do with it. Here is the same source file ran with accruing optimizations:

```
$ ./bisect.sh src/eqtest.c
===========================
Added OptDeadJumps
bad: 1
good: 1
===========================
Added OptRTS
bad: 1
good: 1
===========================
Added OptDeadCode
bad: 1
good: 1
===========================
Added OptCmp8
bad: 1
good: 1
===========================
Added OptCmp3
bad: 1
good: 1
===========================
Added OptUnusedLoads
bad: 1
good: 1
===========================
Added OptDupLoads
bad: 1
good: 1
===========================
Added OptStackOps
bad: 0
good: 1
===========================
Added OptSize1
bad: 0
good: 1
===========================
Added OptSize2
bad: 0
good: 1
```

Diff between the two optimizations:

```diff
**** tmp/8.snip   2016-08-25 19:22:25.000000000 -0700
--- tmp/9.snip    2016-08-25 19:22:25.000000000 -0700
***************
*** 1,20 ****
! Code after applying `OptDupLoads':
  .segment        "CODE"

            lda     #$7E
            jsr     pusha
            lda     #<(L0004)
            ldx     #>(L0004)
            jsr     pushax
!           ldx     #$00
!           lda     #$00
!           jsr     pushax
!           ldy     #$04
            lda     (sp),y
            and     #$01
!           jsr     toseqax
            jsr     pushax
            ldy     #$04
            jsr     _printf
            lda     #<(L0009)
            ldx     #>(L0009)
--- 1,20 ----
! Code after applying `OptStackOps':
  .segment        "CODE"

            lda     #$7E
            jsr     pusha
            lda     #<(L0004)
            ldx     #>(L0004)
            jsr     pushax
!           ldy     #$02
            lda     (sp),y
            and     #$01
!           cpx     #$00
!           bne     L000F
!           cmp     #$00
! L000F:          jsr     booleq
            jsr     pushax
            ldy     #$04
            jsr     _printf
            lda     #<(L0009)
            ldx     #>(L0009)
```

**Comment by acqn** [comment] 2019-12-30 14:26
OptStackOps removes the only `ldx     #$00` left that was responsible for setting the correct hibyte for the tos int16 cmp (as a result of OptDupLoads). The "proper fix" should be to detect such cases and readd the loads if necessary, but could it be sufficient just to reorder OptDupLoads/OptStackOps?

**Comment by oliverschmidt** [comment] 2020-06-22 21:27
Fixed with https://github.com/cc65/cc65/pull/1053.

**Closed by oliverschmidt** 2020-06-22 21:27 UTC
Labels: bug, help wanted
