### ISSUE TITLE
The GitHub Actions based Windows snapshots are zipped .zips

### ISSUE THREAD

**Issue by oliverschmidt** [cc65/cc65#1693] opened 2022-03-01 17:16 UTC
As far as I see the currently generated .zips contain .zips. I'm wondering if this is intended.

**Comment by greg-king5** [comment] 2022-03-01 21:47
Blame Github!  It compresses the download -- even though the file already is compressed!

**Comment by mrdudz** [comment] 2022-03-01 21:54
Why did you remove the tags? This should be fixed!

**Comment by greg-king5** [comment] 2022-03-01 22:55
cc65's build-system doesn't have a bug!  The bug is in Github.  I removed those labels because they don't belong here!  There is nothing for us to fix.  Github needs to fix _their_ bug.  There's nothing that we can do about it.

Those labels should be removed, they don't belong here.

**Comment by mrdudz** [comment] 2022-03-01 23:05
I am sure we can make it so it uploads a zip that doesnt contain another zip. Whose fault it is is irrelevant, blaming github doesnt help anyone, it should be fixed in one way or another.

**Comment by mrdudz** [comment] 2022-03-01 23:21
also i have just again clicked on the "windows snapshot" link on the website and then checked the file using cmdline unzip:
```
$ unzip -v cc65-snapshot-win32.zip
Archive:  cc65-snapshot-win32.zip
 Length   Method    Size  Cmpr    Date    Time   CRC-32   Name
--------  ------  ------- ---- ---------- ----- --------  ----
  329429  Defl:N    98494  70% 03-01-2022 19:56 651ef8b7  bin/ar65.exe
  555716  Defl:N   178546  68% 03-01-2022 19:56 68cb5f5a  bin/ca65.exe
  836428  Defl:N   304637  64% 03-01-2022 19:56 9672d14f  bin/cc65.exe
  310420  Defl:N    91995  70% 03-01-2022 19:56 c0f587e5  bin/chrcvt65.exe
  349164  Defl:N   104703  70% 03-01-2022 19:56 3102b407  bin/cl65.exe
  322395  Defl:N    96795  70% 03-01-2022 19:56 708b838d  bin/co65.exe
  392650  Defl:N   115304  71% 03-01-2022 19:56 30580e8f  bin/da65.exe
  319973  Defl:N    96352  70% 03-01-2022 19:56 c0e9ce22  bin/grc65.exe
  433799  Defl:N   140784  68% 03-01-2022 19:56 6bc7bd08  bin/ld65.exe
  323854  Defl:N    97700  70% 03-01-2022 19:56 f767338c  bin/od65.exe
  344748  Defl:N    99337  71% 03-01-2022 19:56 177ce6a1  bin/sim65.exe
  347454  Defl:N   107602  69% 03-01-2022 19:56 065b268c  bin/sp65.exe
```
so what exactly are we even talking about here? lol!

**Comment by oliverschmidt** [comment] 2022-03-02 11:42
Trying to make sure that there's no unnecessary misunderstanding...

I'm talking about these links:

![image](https://user-images.githubusercontent.com/2664009/156353664-a6e8cf77-459e-4eb3-8da0-116b4e483ff1.png)

Using Chrome on Windows 10 (what I presume to be a pretty usual setup) clicking on the top link I get downloaded a file named `cc65-snapshot-win32.zip.zip`.

Double clicking that file without having any unarchiving tool installed triggers the Windows File Explorer ZIP file handler which displays ``cc65-snapshot-win32.zip`.

The Windows File Explorer ZIP file handler doesn't support recursion so that a user without unarchiving tool installed is lost here :-(

With WinRAR installed things look like this:

![image](https://user-images.githubusercontent.com/2664009/156355271-b5de2b75-cc12-4611-8d08-19308855f7c2.png)

**Comment by mrdudz** [comment] 2022-03-02 11:56
Uuuuh. I never even clicked on those - those are so well hidden no normal user will ever see them anyway. Those are, as the caption says, artefacts - take them as they are (and like greg said, we cant do much about it, unless jumping through a bunch of ugly hops) :) And i am sure a user who even manages to find those will figure out how to depack them too :=) For everyone else the link on the website works fine. In the future we will publish the snapshots as prereleases, which should solve this too.

**Closed by mrdudz** 2022-03-02 11:56 UTC
Labels: bug, buildsystem

**Comment by oliverschmidt** [comment] 2022-03-02 12:20
Are you talking about https://sourceforge.net/projects/cc65/files/cc65-snapshot-win32.zip ? At some point I was told that this file wasn't automatically updated anymore and that I would have to resort to the Actions artifacts. I guess I'm supposed to interpret closing the issue at hand as that restriction not being in place anymore, right?

**Comment by mrdudz** [comment] 2022-03-02 12:28
That was fixed a while ago :) So indeed, that file is up to date and the link from the website points to it and works as intended

**Comment by oliverschmidt** [comment] 2022-03-02 13:28
Great :-)
