### ISSUE TITLE
cc65: Wrong line number in error message

### ISSUE THREAD

**Issue by kugelfuhr** [cc65/cc65#1787] opened 2022-07-05 14:10 UTC
This code:

```C
#define x       3
#define f(a)    f(x * (a))
#undef  x
#define x       2
#define g       f
#define z       z[0]
#define h       g(~
#define m(a)    a(w)
#define w       0,1
#define t(a)    a
#define p()     int
#define q(x)    x
#define r(x,y)  x ## y
#define str(x)  # x

f(y+1) + f(f(z)) % t(t(g) (0) + t)(1);
g(x+(3,4)-w) | h 5) & m(f)^m(m);
p() i[q()] = { q(1), r(2,3), r(4,), r(,5), r(,) };
char c[2][6] = { str(hello), str() };
```

when translated with "cc65 -E test.c" generates an error message with an invalid line number:

```
test.c(0): Error: Macro argument count mismatch
```

The resulting preprocessed output is also wrong, but this is probably not worth mentioning since the preprocessor doesn't have a problem, it *is* a problem :grinning: 

Maybe someone could at least fix the not very helpful line number in the message.

**Comment by acqn** [comment] 2022-07-05 16:16
The line number is 0 because `CloseIncludeFile()` is somehow called from `NextLine()` inside `ExpandMacro()`. No clue how to fix that though.

**Comment by kugelfuhr** [comment] 2022-07-05 18:52
> The line number is 0 because `CloseIncludeFile()` is somehow called from `NextLine()` inside `ExpandMacro()`. No clue how to fix that though.

You can try this for a start:

```diff
diff --git a/src/cc65/input.c b/src/cc65/input.c
index 22a66e1f7..8504ab91d 100644
--- a/src/cc65/input.c
+++ b/src/cc65/input.c
@@ -102,6 +102,9 @@ static Collection AFiles = STATIC_COLLECTION_INITIALIZER;
 /* Input stack used when preprocessing. */
 static Collection InputStack = STATIC_COLLECTION_INITIALIZER;
 
+/* Main file structure */
+static AFile* MainFile = 0;
+
 
 
 /*****************************************************************************/
@@ -241,9 +244,6 @@ static IFile* FindFile (const char* Name)
 void OpenMainFile (const char* Name)
 /* Open the main file. Will call Fatal() in case of failures. */
 {
-    AFile* MainFile;
-
-
     /* Setup a new IFile structure for the main file */
     IFile* IF = NewIFile (Name, IT_MAIN);
 
@@ -343,8 +343,10 @@ static void CloseIncludeFile (void)
         PopSearchPath (UsrIncSearchPath);
     }
 
-    /* Delete the active file structure */
-    FreeAFile (Input);
+    /* Delete the active file structure if it is not the main file */
+    if (Input != MainFile) {
+        FreeAFile (Input);
+    }
 }
 
 
@@ -560,8 +562,8 @@ unsigned GetCurrentLine (void)
         const AFile* AF = (const AFile*) CollAt (&AFiles, AFileCount-1);
         return AF->Line;
     } else {
-        /* No open file */
-        return 0;
+        /* No open file, use the main file if we have one. */
+        return MainFile? MainFile->Line : 0;
     }
 }
```

**Comment by acqn** [comment] 2022-07-23 02:54
Thanks for the suggestion. However, that won't help much with included files.

The problem is that the PP disgnostic messages asked for the "currently opened" source file info that which was changed while the PP parser was trying to obtain the actual arguments for the function-like macro. Unless the correct source file info was somehow kept like that for non-PP disgnostics, the bug can't be fully fixed with a hack for the non-included source file only.

**Comment by kugelfuhr** [comment] 2022-07-24 04:52
I beg to differ.

In theory, a diagnostic should point to the actual location of an error. In reality the error is often spotted a few tokens later depending on its nature. Every programmer knows this behavior. If these "few tokens later" are at the end of the input file, the error message should not contain some funny non-existing and unhelpful line number but the last line number in the input
file. This is what my patch achieves. It keeps the information about the input file alive in case it is needed. So it is definitely not a "hack" but fixes a problem with the original code.

You may of course __in addition__ to that improve the preprocessor so that the error is spotted earlier and a more accurate error location can be output.

Compare this to a missing comment delimiter. If "*/" is missing and the scanner runs to the end of the input, would you accept an error message saying _"error in line 0"_? No, of course not. But this is what the current code does in case of the input presented by me.

The first and most obvious fix in case of an unterminated comment would be to let it point to the end of the input where the error is detected instead of printing _"error in line 0"_. A second step would be to record the start of the comment so _"end of file in comment starting at ..."_ can be output.

Or to look at it from another view point: Even if you fix the problem in the preprocessor and diagnose the error earlier, you can never be sure that the next preprocessor bug (and there are many!) will not again cause a diagnostic with a non-existing line number.

The code that retrieves the line number is simply wrong and this has to be fixed. Which is what my change does.

**Comment by acqn** [comment] 2022-07-25 03:04
You have a point. Your patch isn't a hack, and the resolution of these issues can be done increamently.

**Closed** 2022-08-19 19:37 UTC
Labels: bug, cc65
