### ISSUE TITLE
cc65 fails to warn about a function returning struct

### ISSUE THREAD

**Issue by clbr** [cc65/cc65#264] opened 2016-01-27 18:52 UTC
This program gives wrong results when built on cc65, regardless of -O. The function is correct, and it succeeds when built on gcc.

(I was looking for a faster div() alternative. Still need to try a modified stdlib div() that uses unsigned division instead.)

```
#include <nes.h>
#include <conio.h>
#include <stdio.h>
#include <stdlib.h>
#include <stdint.h>

typedef uint16_t u16;
typedef uint8_t u8;

typedef struct {
    u16 quot;
    u16 rem;
} udiv_t;

udiv_t div3(u16 in) {

    udiv_t u;
    u16 q = 0;

    while (in >= 300) {
        in -= 300;
        q += 100;
    }

    while (in >= 30) {
        in -= 30;
        q += 10;
    }

    while (in >= 3) {
        in -= 3;
        ++q;
    }

    u.quot = q;
    u.rem = in;

    return u;
}

int main() {

    u16 i;
    div_t d;
    udiv_t u;

    for (i = 1024; i; i--) {
        d = div(i, 3);
        u = div3(i);

        if (d.quot != u.quot || d.rem != u.rem) {
            cprintf("Mismatch at %u/3, div %u %u, div3 %u %u\n", i,
                d.quot, d.rem, u.quot, u.rem);
            break;
        }
    }

    while (1);

    return 0;
}
```

**Comment by clbr** [comment] 2016-01-27 18:59
Sorry, my mistake. "C Functions may not return structs". It's asm or nothing to return structs.

**Comment by greg-king5** [comment] 2016-02-08 16:07
Please re-open this issue; and, change its title to
 "cc65 fails to control the passing of structs to and from functions."

Oliver, please label this with **bug**.

- cc65 blindly tries to pass structs -- but usually, it fails.
- cc65 fails to tell us that it can't pass structs.

**Comment by acqn** [comment] 2020-07-09 14:40
A fix for #1075 + #1077 could affect this. What is the expected behavior?

**Comment by mrdudz** [comment] 2020-07-09 14:51
If you can actually make it work, why not :) But unless that is the case, it should produce an error IMHO

**Comment by polluks** [comment] 2020-07-09 15:01
cc65.sgml says: "C Functions may not return structs (or unions), and structs may not be passed as parameters by value."
You may remove this statement afterwards.

**Comment by oliverschmidt** [comment] 2020-07-09 15:13
> If you can actually make it work, why not :) But unless that is the case, it should produce an error IMHO

Maybe your style of humor can be misinterpreted. I presume you wanted to express that it would of course be great if it would work.

**Comment by mrdudz** [comment] 2020-07-09 15:15
Oh yes, of course!

**Comment by acqn** [comment] 2020-07-11 14:44
> 
> 
> If you can actually make it work, why not :)

But... how is it supposed to work? Pass by value a struct <= 4 bytes sized in EAX and just emit a compile error for other sizes? Is there an ABI constaint?

**Comment by oliverschmidt** [comment] 2020-07-11 15:03
> Pass by value a struct <= 4 bytes sized in EAX and just emit a compile error for other sizes?

Maybe (or even likely) I'm missing the point, but that would seem reasonable to me.

> Is there any ABI constaint for a given calling convention?

Sorry, but I don't understand that question :-(

**Comment by polluks** [comment] 2020-07-11 15:36
@oliverschmidt acqn wants to know if we have any 64-bit support.

**Comment by mrdudz** [comment] 2020-07-11 16:01
> But... how is it supposed to work?

I seriously have no idea. i would probably look at what works best for the case when a returned struct is directly passed into a function that takes a struct.

That said i hardly return structs by value, ever (on any target) :)

**Comment by greg-king5** [comment] 2020-07-11 17:04
> But... how is it supposed to work? Pass by value a struct <= 4 bytes sized in EAX, and just emit a compile error for other sizes?

Yes, that was the plan:
- one-byte structs in `__A__`
- two-byte structs in `__AX__`
- three-byte and four-byte structs in `__EAX__`

**Comment by greg-king5** [comment] 2020-07-11 17:47
Another idea is to detect this kind of statement:
```c
<struct_variable> = <function_returning_struct>();
```
Then, compiling it as though it were:
```c
<struct_variable> = *(<function_returning_pointer_to_struct>());
```
If there are no C-level interrupts, then that immediate block-copy will be able to handle structs that are defined in the function as "automatic" variables.

**Comment by polluks** [comment] 2020-07-11 19:20
@greg-king5 Nice, would this still be portable?

**Comment by greg-king5** [comment] 2020-07-11 21:14
> @greg-king5 Nice, would this still be portable?

I assume so.

We can do something similar to that -- now -- with macros.  The current limited cc65 support was designed for the stdlib `div()` function.  A long time ago, I experimented with an implementation for `ldiv()`.
```c
typedef struct {
    long quot;
    long rem;
} ldiv_t;

extern ldiv_t * __fastcall__ _ldiv_(long numer, long denom);
#define ldiv(n,d) (*_ldiv_(n,d))
```
I was able to use expressions such as:
```c
ldiv_t svar;
long lvar;

svar = ldiv(128, 7);
lvar = ldiv(37, 5).rem + 1L;
```

**Comment by acqn** [comment] 2020-07-12 04:06
> 
> 
> > Is there any ABI constaint for a given calling convention?
> 
> Sorry, but I don't understand that question :-(

Sorry I made a typo. I was asking about if there has been an established or planned ABI specification for cc65 on how a struct is returned by value from a function. True that it won't be very useful if only a <= 4 bytes struct can be returned by value as a 64-bit integer (or a pair of 32-bit longs) takes up at least 8 bytes.

**Comment by oliverschmidt** [comment] 2020-07-12 10:28
> I was asking about if there has been an established or planned ABI specification for cc65 on how a struct is returned by value from a function.

No, there's nothing like that.

**Comment by acqn** [comment] 2020-07-15 12:06
Now I've fixed passing to and returning from functions structs <= 4 bytes by value. Struct > 4 bytes to and from functions by value are simply rejected in compile errors. Is this good enough?

**Comment by oliverschmidt** [comment] 2020-07-15 12:08
At least to me that's the most reasonable approach - and meets at least my expectations best :-)

**Comment by clbr** [comment] 2020-07-15 12:15
Yes, ok to close.

**Comment by oliverschmidt** [comment] 2020-07-15 12:33
Usually we close an issue when the pull request fixing it gets merged.

**Comment by clbr** [comment] 2020-07-15 12:49
Oh, from acqn's reply it sounded like it was already merged.

**Comment by oliverschmidt** [comment] 2020-07-15 12:51
In that case: Which is
the relevant pull request/commit?

**Comment by acqn** [comment] 2020-07-16 03:09
> 
> 
> In that case: Which is the relevant pull request/commit?

Delayed due to some spotted bugs related to bitfields.

**Comment by oliverschmidt** [comment] 2020-07-16 07:17
Okay, then there was _no_ misunderstanding between the two of us :-)

**Comment by acqn** [comment] 2020-07-16 08:22
Is it still necessary to warn about passing structs/unions to functions when they work right?

**Comment by oliverschmidt** [comment] 2020-07-16 08:25
Maybe I'm missing the point but my expection would be:

- struct <= 4 bytes: everything compiles smoothly
- struct > 4 bytes: "hard" error

**Comment by greg-king5** [comment] 2020-07-16 18:39
> Is there still a point to warn about passing structs/unions to functions by value when they are working right (<= 4 bytes)?

When a struct/union expression can be compiled, say nothing.   When it cannot, complain.

**Comment by acqn** [comment] 2020-07-18 13:29
So... we'll keep the "struct-param" warning available while disabling it by default, or just remove it?

**Comment by oliverschmidt** [comment] 2020-07-18 19:13
Please remove it.

**Closed** 2020-07-19 08:58 UTC
Labels: bug
