### ISSUE TITLE
[ca65] .define fails with single letter parameters

### ISSUE THREAD

**Issue by FrostyHitoshura** [cc65/cc65#1283] opened 2020-10-09 22:50 UTC
Minimal way to reproduce the problem:

```
$ echo ".define DEF(x) x" | ca65 /dev/stdin -o /dev/null
/dev/stdin(1): Error: ')' expected
$ echo ".define DEF(x0) x0" | ca65 /dev/stdin -o /dev/null
[no output, it compiled successfully]
$ ca65 --version
ca65 V2.18 - Fedora 2.18-12.fc32
```

**Comment by polluks** [comment] 2020-10-09 23:40
x like register x, that's the cause.

**Comment by greg-king5** [comment] 2020-10-10 12:15
This issue is a duplicate of #392.

**Closed** 2020-10-10 12:16 UTC
Labels: duplicate
