### ISSUE TITLE
inline asm: cc65 chokes on label ref if space/tab follows

### ISSUE THREAD

**Issue by marcobaye** [cc65/cc65#1252] opened 2020-09-08 20:39 UTC
this works:
```
asm(
"label: inx\n"
"       bne label\n"
);
```
but this does not:
```
asm(
"label: inx\n"
"       bne label        \n"
);
```
cc65 compiles it, but ld65 then complains about an unresolved external.
cc65 seems to count trailing spaces or TABs in label refs as part of the label name, so the matching label is not found and therefore not marked as referenced. the label definition is then dropped, at least it does not show up in the .s file, and so ld65 rightfully complains.

Here's a patch to fix it, though I guess it's not the "right" way to do it (it removes all trailing whitespace from inline asm lines).
```
diff --git a/src/cc65/codegen.c b/src/cc65/codegen.c
index 9e510272..7a9d5930 100644
--- a/src/cc65/codegen.c
+++ b/src/cc65/codegen.c
@@ -4370,5 +4370,19 @@ void g_switch (Collection* Nodes, unsigned DefaultLabel, unsigned Depth)
 void g_asmcode (struct StrBuf* B)
 /* Output one line of assembler code. */
 {
-    AddCodeLine ("%.*s", (int) SB_GetLen (B), SB_GetConstBuf (B));
+    int len = (int) SB_GetLen(B);
+    const char *buf = SB_GetConstBuf(B);
+
+    /* remove whitespace at end of line so it does not interfere with label refs */
+    while (len) {
+       switch (buf[len - 1]) {
+       case '\n':
+       case ' ':
+       case '\t':
+           --len;
+           continue;
+       }
+       break;
+    }
+    AddCodeLine ("%.*s", len, buf);
 }
```

**Comment by acqn** [comment] 2020-09-08 23:10
At the moment, labels are not supposed to be written directly in the asm strings. C labels should be used instead.

**Comment by jmr** [comment] 2020-09-09 06:53
> At the moment, labels are not supposed to be written directly in the asm strings. C labels should be used instead.

Then is the right solution to give an error/warning for labels in inline assembly?

Why aren't they supposed to be used, if they apparently work, at least in some cases?

**Comment by acqn** [comment] 2020-09-09 12:52
You are right. They should be fixed so that they could work in all cases.

**Comment by oliverschmidt** [comment] 2020-09-09 14:40
What about name clashes with labels generated by the compiler?

In general my understanding was/is that the inline assembler is deliberately about 6502 instructions, not about assembler commands/directives/<...>. I understand the concept behind the inline assembler rather in that way that one could exchange ca65 as compiler backend with another assembler having probably a totally different understanding of labels and still have all existing inline assembly working. I do NOT understand inline assembler as a sort of pass-through mechanism to write ca65 source code.

I would be VERY reluctant to merge a change that tries to put the inline assembler into a different perspective.

**Comment by oliverschmidt** [comment] 2020-09-09 14:45
https://cc65.github.io/doc/cc65.html#s9 says: 

_The contents of the string literal are preparsed by the compiler; and, inserted into the generated assembly output, so that it can be processed further by the backend -- and, especially the optimizer. For that reason, the compiler does allow only regular 6502 opcodes to be used with the inline assembler. Pseudo instructions (like .import, .byte, and so on) are not allowed, even if the ca65 assembler (which is used to translate the generated assembler code) would accept them. The built-in inline assembler is not a replacement for the full-blown macro assembler which comes with the compiler._

That's pretty clear from my POV. Therefore I classify this issue as question. The answer is 'Works as designed'.

**Comment by oliverschmidt** [comment] 2020-09-09 14:48
> Then is the right solution to give an error/warning for labels in inline assembly?

From my POV: 'Yes'. I'd appreciate a PR that makes cc65 more strict about what it accepts as inline assembly.

**Comment by marcobaye** [comment] 2020-09-09 17:44
> At the moment, labels are not supposed to be written directly in the asm strings. C labels should be used instead.
That would make my code much harder to read, because I'd have to split the asm string into two parts to insert the label etc. Still, I tried that, but I could not get the branch to reference the C label at all. Is there an official example on how this is supposed to work?

> What about name clashes with labels generated by the compiler?
I guess those would result in error messages, so there would need to be some kind of naming rule(s). Not a thing I'm fond of, but I would find an ad-hoc rule like "your labels must begin with the letter q" much easier to stomach than "you can't use branches in inline asm" (which the reactions to this issue seem to indicate).

> In general my understanding was/is that the inline assembler is deliberately about 6502 instructions, not about assembler commands/directives/<...>.
I agree completely. So how are branch instructions supposed to be written in inline asm then?

**Comment by greg-king5** [comment] 2020-09-09 17:46
The issue is about trailing whitespace, not about the source of labels.  This code has the same problem:
```asm
c_label:
  asm("inx\n"
      "bne %g        \n",
      c_label);
```

**Comment by oliverschmidt** [comment] 2020-09-09 18:54
> So how are branch instructions supposed to be written in inline asm then?

https://cc65.github.io/doc/cc65.html#s9 says:

_%g - Assembler name of a C label_

> Is there an official example on how this is supposed to work?

https://cc65.github.io/doc/cc65.html#s9 says:

```
[...]
            __asm__ ("bcs %g", jumpSubNoError);
            __asm__ ("lda #$FF");
        jumpSubNoError:
[...]
```

Maybe you want to have a look at that chapter if using the inline assembler...

**Comment by mrdudz** [comment] 2020-09-09 20:31
> I understand the concept behind the inline assembler rather in that way that one could exchange ca65 as compiler backend with another assembler having probably a totally different understanding of labels and still have all existing inline assembly working.

oh come on. that assembler would have to be so much like ca65 in other aspects, it doesnt really make sense (and labels would be the least of your problems).

> I'd appreciate a PR that makes cc65 more strict about what it accepts as inline assembly.

I'd like to see local labels being accepted, and any other labels rejected. Because using C labels like in the given example is just terrible. IMHO. It also makes it impossible to properly use "asm volatile", may it ever be supported.

That said, i hardly ever use inline asm myself - because of those weird restrictions (and missing volatile).

**Comment by oliverschmidt** [comment] 2020-09-09 20:34
> It also makes it impossible to properly use "asm volatile", may it ever be supported.

Can you elaborate on this aspect? I can't follow you.

**Comment by mrdudz** [comment] 2020-09-09 20:41
Usually (in all other toolchains i used at least) all code within one "asm volatile" statement goes to the output asm file unmodified (the volatile tells the optimizer that it cant touch it). so if you have a code snippet that you dont want the optimizer to touch, you must use one asm statement (multiline), and you cant split it in half to throw in a c-label. ie the "asm volatile" can only guarantee that the optimizer does not touch whats in a single asm statement, no more no less. Yes, likely for cc65 it wont matter, because the optimizer wont reorder things just because of an inserted c label - relying on it is still bad though.

**Comment by acqn** [comment] 2020-09-09 21:48
> The issue is about trailing whitespace, not about the source of labels.

Sorry I didn't clarify that. I was not commenting on the issue. I was commenting on the example in the OP, which could run into...

> What about name clashes with labels generated by the compiler?

If the name clashes then the user is responsible for that and should accept whatever consequence of that, I think.

**Comment by acqn** [comment] 2020-09-09 22:00
> 
> 
> Usually (in all other toolchains i used at least) all code within one "asm volatile" statement goes to the output asm file unmodified (the volatile tells the optimizer that it cant touch it). so if you have a code snippet that you dont want the optimizer to touch, you must use one asm statement (multiline), and you cant split it in half to throw in a c-label. ie the "asm volatile" can only guarantee that the optimizer does not touch whats in a single asm statement, no more no less. Yes, likely for cc65 it wont matter, because the optimizer wont reorder things just because of an inserted c label - relying on it is still bad though.

I think there is "asm volatile" in cc65, but only function-wide:
https://cc65.github.io/doc/cc65.html#s9
> As a shortcut, you can put the volatile qualifier in your asm statements. _It will disable optimization for the functions in which those asm volatile statements sit._ The effect is the same as though you put #pragma optimize(push, off) above those functions, and #pragma optimize(pop) below those functions.

The optimizer currently can't skip optimization only for selective entries in a function. It wouldn't be much easier to fix that than to support `volatile` qualifier.

**Comment by mrdudz** [comment] 2020-09-10 09:14
> I think there is "asm volatile" in cc65, but only function-wide:

yeah, that's another thing that doesn't make it very useful (to me).

**Comment by oliverschmidt** [comment] 2020-09-10 09:30
> yeah, that's another thing that doesn't make it very useful (to me).

It's not another thing. it's __*THE*__ thing. I just don't see a realistic use case for inline asm without it:

If I want to combine large asm portions with little C code I can use the regular assembler right away.
If I want to combine large C portions with little asm code I need to be able to optimize the C code.

So without a momentum to solve that issue I don't see any point at all in other changes (improvements?) to the inline assembler - in fact not even a point in discussing them. Therefore my opinion to not discuss asm labels.

**Comment by mrdudz** [comment] 2022-08-27 00:12
The most interesting question wasnt answered yet - does the patch in the OP have any undesired side effects?

**Comment by mrdudz** [comment] 2022-08-28 01:59
Fixed the root cause of the problem - and applied your patch anyway, since it seems to be desirable to remove trailing whitespace from inline asm anyway.

cheers :)

**Closed by mrdudz** 2022-08-28 01:59 UTC
Labels: bug, cc65
