### ISSUE TITLE
Foward label reference in C code generates a word

### ISSUE THREAD

**Issue by andre-paris** [cc65/cc65#919] opened 2019-06-28 18:42 UTC
Take this code as example:
```c
void f(void){
    if (1) goto label;

label:
    while(1) {
    }	    
}
```
compiling it with `cc65 -t nes -Oirs test.c` generates this assembly code:
```asm
.segment	"CODE"

.proc	_f: near

.segment	"RODATA"

L0005:
	.word	$0000

.segment	"CODE"

L000C:	jmp     L000C

.endproc
```
look at the L0005, is it correct?
In several places in my games it's generates the .word into a "CODE" segment making a lot of BRK.
Tested with cc65 V2.18 - Git e34ee329

**Comment by greg-king5** [comment] 2019-06-30 04:16
Compile it without optimization.  You'll see the code that cc65 generates when a `goto` jumps into a nested code block which has automatic (stack) variables.

I suspect that the bug is a side-effect of cc65's computed-goto code.

**Comment by oliverschmidt** [comment] 2019-06-30 06:27
Yeah, it's likely a "regression" introduced by fixing the gotos.

**Comment by MonteCarlos** [comment] 2019-07-02 10:58
It looks like the compiler wants to allocate space for a non existant
variable.
Probably it interpretes the constant '1' as an int variable and then
accidentially emits the

L0005:
	.word	$0000
.

I went back to commit 55ce618bf2e64b2b4331a7f7a41223e3e6933492
and i can tell that the "bug" was already there.

Monte Carlos

Am 28.06.2019 um 20:42 schrieb André Paris de Oliveira:

**Comment by andre-paris** [comment] 2019-07-02 15:34
> Probably it interpretes the constant '1' as an int variable and then accidentially emits the

I don't this that's the cause, this code
```c
void f(void){
    goto label;

    label:
    	return;	    
}
```
compiles to: (-Oirs)
```asm
; ---------------------------------------------------------------
; void __near__ f (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_f: near

.segment	"RODATA"

L0003:
	.word	$0000

.segment	"CODE"

	rts

.endproc
```
w/o any optimizations:
```asm
; ---------------------------------------------------------------
; void __near__ f (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_f: near

.segment	"RODATA"

L0003:
	.word	$0000

.segment	"CODE"

	pha
	lda     L0003
	clc
	adc     sp
	sta     sp
	lda     L0003+1
	adc     sp+1
	sta     sp+1
	pla
	jmp     L0002
L0002:	jmp     L0001
L0001:	rts

.endproc
```

**Comment by MonteCarlos** [comment] 2019-07-03 21:00
I see. Your new testprog is more minimal and it also reproduces the
previous result.
So it would make up a better testcase.
However, 37f00e664454e98196fc7058d1de8e0f6dae99f5
produces still the same code.

Anyhow, the

.word	$0000
is in the RODATA, not the CODE segment and should not cause so much trouble.

Am 02.07.2019 um 17:34 schrieb André Paris de Oliveira:

**Comment by andre-paris** [comment] 2019-07-03 22:23
So look at this one:
```c
#pragma rodata-name(push, "CODE")
const unsigned char CONST[] = {0, 1, 2};

#pragma code-name(push, "CODE")
void f(void){
    goto label;

    label:
    	return;	    
}
```
you get 
``` asm
.segment	"RODATA"

.segment	"CODE"
_CONST:
	.byte	$00

; ---------------------------------------------------------------
; void __near__ f (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_f: near

.segment	"CODE"

L0006:
	.word	$0000

.segment	"CODE"

	rts

.endproc
```
I used CODE just to simplify, the bug happens when you must emit some bytes in the same segment of a proc ... but if you pop the rodata `rodata-name(pop),` before push the code `code-name(pop)` the result is the same as previous

**Comment by groessler** [comment] 2019-07-03 22:42
```
#pragma rodata-name(push, "CODE")
...
#pragma code-name(push, "CODE")
```

Why do you do that? Could you give the reasoning behing it?

I'm considering this as a typical case of "shooting oneself into the foot".

Still, the emitted word is not needed, I agree. But with this snippet above you've turned a non-optimal compilation output to a buggy compilation output.

**Comment by greg-king5** [comment] 2019-07-04 02:56
You should pop as soon as you have finished defining the objects that you want to put in a different segment:
```c
#pragma rodata-name(push, "CODE")
const unsigned char CONST[] = {0, 1, 2};
#pragma rodata-name(pop)

void f(void){
    goto label;

label:
    ;
}
```

**Comment by greg-king5** [comment] 2019-07-04 03:35
A more complex example:
```c
#include <conio.h>

#pragma code-name("ROM")

#pragma rodata-name(push, "ROM")
const unsigned char CONST[] = {0, 1, 2};

#pragma rodata-name("BOGUS")
void f(void)
{
    cputs("A string literal\r\n");
    goto label;

label:
    ;
}
#pragma rodata-name(pop)
```
generates
```asm
.segment	"RODATA"

.segment	"ROM"
_CONST:
	.byte	$00
	.byte	$01
	.byte	$02
.segment	"BOGUS"
.segment	"RODATA"
L000A:
	.byte	$41,$20,$73,$74,$72,$69,$6E,$67,$20,$6C,$69,$74,$65,$72,$61,$6C
	.byte	$0D,$0A,$00

; ---------------------------------------------------------------
; void __near__ f (void)
; ---------------------------------------------------------------

.segment	"ROM"

.proc	_f: near

.segment	"BOGUS"

L000D:
	.word	$0000

.segment	"ROM"

	lda     #<(L000A)
	ldx     #>(L000A)
	jmp     _cputs

.endproc
```

**Comment by oliverschmidt** [comment] 2020-06-01 20:40
Fixed by https://github.com/cc65/cc65/pull/1041.

**Closed by oliverschmidt** 2020-06-01 20:40 UTC
Labels: bug
