### ISSUE TITLE
[goto] Innocent goto takes more memory now

### ISSUE THREAD

**Issue by Fabrizio-Caruso** [cc65/cc65#769] opened 2018-10-05 06:26 UTC
I have followed the recent goto fixes.
It seems that this has a negative effect on innocent goto's:
```c
if(oneMissileLevel())
{
	if(bulletPtr->_x==XSize-1 && bulletPtr->_y==YSize/2 && rightHorizontalMissile._status)
	{
		goto _destroy; // destroyHorizontalMissile(&rightHorizontalMissile);
	}
}				
else if(missileLevel() || bossLevel())
{
	if(bulletPtr->_x==XSize-1 && bulletPtr->_y==HORIZONTAL_MISSILE_OFFSET && rightHorizontalMissile._status)
	{
_destroy:	destroyHorizontalMissile(&rightHorizontalMissile);	
	}
	else if(bulletPtr->_x==0 && bulletPtr->_y==YSize-1-HORIZONTAL_MISSILE_OFFSET && leftHorizontalMissile._status)
	{
		destroyHorizontalMissile(&leftHorizontalMissile);	
	}
}
```
Previously, inserting a goto was beneficial in terms of code size. It is now detrimental.
The difference between the previous code size and the current one is 13 extra bytes for the binary compiled with post-goto-fixed CC65 versions.

**Comment by greg-king5** [comment] 2018-10-05 20:05
Yep!  We might be able to fix that problem -- someday.  In the meantime, use inline Assembly code (it doesn't add the 13-byte preamble):
```c
#ifdef __cc65__
		asm("jmp %g", _destroy); // destroyHorizontalMissile(&rightHorizontalMissile);
#else
		goto _destroy; // destroyHorizontalMissile(&rightHorizontalMissile);
#endif
```

**Comment by mrdudz** [comment] 2018-10-05 21:27
a bug has been fixed, and the result was increased code size. that in itself is not a bug. thats why.

**Comment by Fabrizio-Caruso** [comment] 2018-10-05 21:53
@mrdudz Strictly speaking it is not a bug. But it makes using GOTO pointless. GOTO's main use is to escape nested loops or complex flows and so avoid the cost of flag variables or extra checks
Fixing the bug was important but we now have a little problem that should be tracked somehow.

**Comment by mrdudz** [comment] 2018-10-05 22:09
goto works just like before (no, it now works right). there is no bug. some impact is expected. you can fix your program instead, like use a subroutine that exits with return instead - which is probably the better idea anyway.

**Comment by silverdr** [comment] 2018-10-05 22:15
@mrdudz - the "naive" gotos were probably the cheapest in terms of code size. The closest "emulation" of them is what Greg proposed at the beginning.

**Comment by silverdr** [comment] 2018-10-05 22:43
That's what I am saying - the closest "emulation" is what Greg proposed. Should be equally cheap.

**Comment by oliverschmidt** [comment] 2018-10-05 23:09
I must admit that I have a somewhat different perspective:

1. I need to confess that I obviously understood https://github.com/cc65/cc65/pull/759 (even) less than I thought so far. I was under the impression that the code generation would only be changed if there were any scope-local variables involved. And that the only scenario in which the resulting code is unnecessarily larger is when the goto origin and the goto destination happen to have the same amount of scope-local variables. I don't want to say that I wouldn't have merged https://github.com/cc65/cc65/pull/759 given my current improved understanding. But I consider this issue "interesting".

2. cc65 is known (and documented?) to generate less-than-optimal code for scope-local variables. Therefore any cc65-targeting source code avoids them in the first place. And such source code could use gotos without any risk in the past. So **in** **general** stating "they never worked right" is at least from my pov not appropriate.

3. At least with a naive-enough perspective on the cc65 optimizer one can imagine that the optimizer could identify the stack pointer adjustment adding/subtracting just a zero in specific scenarios (like the one given in this issue) and therefore could optimize away the whole adjustment.

Apart from my personal perspective above I'm surprised that after...

> Yep! We might be able to fix that problem -- someday.

...this is issue got closed. It seems to ask for being classified as an enhancement instead. I fully agree in seeing it not being closed anytime soon but I think we have quite some less "interesting" enhancement issues open.

Let me close with stating that the unusual harsh reaction on this issue likely comes from the different perspective on classifying it as a regression. I agree that it mustn't be seen as a regression, but it's a new opportunity for an optimization, isn't it?

**Comment by Fabrizio-Caruso** [comment] 2018-10-07 21:57
@mrdudz, @silverdr I agree that this issue is not a bug. It is just an enhancement.
This enhancement is maybe doable in some detectable cases where a simple jmp can be produced without any overhead.
The overhead is fine but it seems to make the goto useless as a flow optimization, which is what it is usually meant to be.
I agree that fixing the bug is much more important. Slow and bigger code is always better than wrong code.

**Comment by laubzega** [comment] 2018-10-12 21:19
Hi guys. Just a heads-up, I'm looking into this. The fix will need the -O to be specified.

**Comment by laubzega** [comment] 2018-10-13 07:14
The first cut is available on goto-opt branch in my fork, if anybody wants to play with it. I should be able to clean it up, add comments and create a PR tomorrow.

**Comment by laubzega** [comment] 2018-10-14 08:18
Now the overhead should be reduced to two bytes per forward goto. They correspond to the 16-bit value of SP adjustment stored in RODATA segment.

In order to do something about them I would need to add quite some extra infrastructure needed for optimization of non-code data. Certainly doable, just not this weekend. ;)

**Comment by oliverschmidt** [comment] 2018-10-14 10:31
> The fix will need the -O to be specified.

This fully meets (at least my personal) expectations.

**Comment by oliverschmidt** [comment] 2018-10-14 11:35
> Now the overhead should be reduced to two bytes per forward goto. They correspond to the 16-bit value of SP adjustment stored in RODATA segment.

Are you saying that if the source and target scope of the goto have the same stack size then optimizer reduces the goto down to the actual JMP so there's no overhead in cycles anymore? Only the size overhead of two bytes is left?

> In order to do something about them I would need to add quite some extra infrastructure needed for optimization of non-code data. Certainly doable, just not this weekend. ;)

In case I got things right (see my question above) I'd rather opt for leaving those two bytes alone and invest your "cc65 contribution budget" more advantageously ;-)

**Comment by Fabrizio-Caruso** [comment] 2018-10-14 12:37
I understand that are some extra 2 byte overhead left on top of the jmp (which I don't see as an overhead in 99% of the cases).
Moreover I am not able to understand why this is done as a sort of post-processing optimization and the innocent goto cannot be detected before the stack adjustment is inserted. I guess this is done this way, because it is easier to implement this way.

**Comment by laubzega** [comment] 2018-10-14 21:34
> Are you saying that if the source and target scope of the goto have the same stack size then optimizer reduces the goto down to the actual JMP so there's no overhead in cycles anymore? Only the size overhead of two bytes is left?

Correct. Other cases have also been improved, reducing code size and/or improving performance if SP adjustment is small enough.

> Moreover I am not able to understand why this is done as a sort of post-processing optimization and the innocent goto cannot be detected before the stack adjustment is inserted.

When the parser encounters a goto that jumps forward, it has no idea yet what SP adjustment is necessary, if at all.  Since it won't be able to go back a fix things later (see silverdr's post above), it has to assume the worst case - a full 16-bit adjustment - and generates such code just before the jump. You could say that all forward gotos are guilty until proven innocent. ;)

The compiler can revisit these jumps during the optimization pass, now fully informed about the actual adjustment values, and reduce the size of pre-jump code, sometimes to zero.


BTW, if the two remaining bytes in RODATA prove bothersome, I have a relatively quick way of removing them, too. It's just that it's not very elegant, and I came to appreciate the elegance of cc65's code after spending some time starting at it. :)

**Comment by Fabrizio-Caruso** [comment] 2018-10-14 21:47
@laubzega thanks for your effort. I understand that there are two wasted bytes somehwhere in rodata. Maybe a clean solution is possible. Otherwise this is already a significant improvement. I have changed my old opinion on gotos. They are useful and very good in some situations and used with care can even make the code more readble (e.g., avoid flag variables, exit nested loops, etc.).

**Comment by silverdr** [comment] 2018-10-15 08:12
@Fabrizio-Caruso - I don't know what your old opinion about gotos was but what you listed as examples are probably the most common "legit" use of them. To the degree that (under different names) they found their way even to languages, which officially don't have "goto" construct.

**Comment by oliverschmidt** [comment] 2018-10-15 10:55
>> Are you saying that if the source and target scope of the goto have the same stack size then optimizer reduces the goto down to the actual JMP so there's no overhead in cycles anymore? Only the size overhead of two bytes is left?

> Correct.

:-)

> Other cases have also been improved, reducing code size and/or improving performance if SP adjustment is small enough.

I understood that from the nice comments.

> BTW, if the two remaining bytes in RODATA prove bothersome, I have a relatively quick way of removing them, too. It's just that it's not very elegant, and I came to appreciate the elegance of cc65's code after spending some time staring at it. :)

I don't see the need for a "hack" here.

**Closed** 2018-10-15 10:56 UTC
Labels: enhancement
