### ISSUE TITLE
files may be checked in with CRLF

### ISSUE THREAD

**Issue by jmr** [cc65/cc65#1237] opened 2020-09-04 10:59 UTC
test/ref/pr1220.c was checked in with CRLFs. (See #1236.) How did the CRLFs even get there? This issue is about the underlying problem, not just that one file.

The commit message for `.gitattributes` says it will force LF.
https://github.com/cc65/cc65/commit/2e8d792f9a1b55bb19942e02b91b1294dbc37e87

It's not clear to me from the documentation that's what happens
https://git-scm.com/docs/gitattributes#Documentation/gitattributes.txt-Settostringvalueauto
"When the file has been committed with CRLF, no conversion is done."

Maybe there should also be `text eol=lf`?
https://git-scm.com/docs/gitattributes#_end_of_line_conversion

Possibly also with `*.vcproj	text eol=crlf`?

**Comment by groessler** [comment] 2020-09-04 12:53
I see that typically when people use Linux/Unix to check-out/check-in the files, but use Windows to edit the files. That's a big no-no!

**Comment by greg-king5** [comment] 2020-09-04 13:44
> The commit message for `.gitattributes` says it will force LF.
> 2e8d792f9a1b55bb19942e02b91b1294dbc37e87
> 
> It's not clear to me from the documentation that that's what happens:
> https://git-scm.com/docs/gitattributes#Documentation/gitattributes.txt-Settostringvalueauto
> "When the file has been committed with CRLF, no conversion is done."

I think that the sentence implies a word:
"When the file _already_ has been committed with CRLF, no conversion is done."
> 
> Maybe there should also be `text eol=lf`?
> https://git-scm.com/docs/gitattributes#_end_of_line_conversion

But, we want Windows Git to add carriage-returns when it checks-out files.
>
> I see that typically when people use Linux/Unix to check-out/check-in the files, but use Windows to edit the files.
> That's a big no-no!

According to the way that I read the docs, `"* text=auto"` is supposed to handle that case.

**Comment by acqn** [comment] 2020-09-04 17:00
I first added an empty `test/ref/pr1220.c`, then replaced it with a CRLF'ed source file and squashed the commits before pushing. Could that be the cause?

**Comment by oliverschmidt** [comment] 2020-09-04 17:56
> Possibly also with *.vcproj text eol=crlf?

Why?

**Comment by oliverschmidt** [comment] 2020-09-04 17:57
> According to the way that I read the docs, "* text=auto" is supposed to handle that case.

Me too.

**Comment by jmr** [comment] 2020-09-04 19:30
> > Possibly also with *.vcproj text eol=crlf?
> 
> Why?

I had mistakenly assumed that the `.vcproj` files would want CRLFs since they're for Windows. They just use LF, so apparently it's not necessary.

**Comment by oliverschmidt** [comment] 2020-09-04 20:54
So we're on the same page :-)

BTW: Visual Studio was one of the first native Windows programs to work flawlessly with LF files - because of devs using mixed Win/*IX setups more frequently than typical Windows users.

**Comment by jmr** [comment] 2020-09-18 06:42
fe3f267 did this again. This really puts git into an unusable state for me since it thinks the files have been modified.

**Comment by oliverschmidt** [comment] 2020-09-18 07:15
I'm too unhappy but I think I've already done what could be done...

**Closed** 2021-03-02 17:05 UTC
Labels: question
