### ISSUE TITLE
Bitfield wrongly printed

### ISSUE THREAD

**Issue by mzattera** [cc65/cc65#1332] opened 2020-11-14 08:32 UTC
The below code prints `b.msb` as `37`, still it evaluates as ==1 in the `if`.
Tested with version `V2.18 - Git 0f66f75`

```C
#include <stdio.h>

struct bitfield {
	unsigned int lsb : 1;
	unsigned int pad : 14;
	unsigned int msb : 1;
};

int main() {
	struct bitfield b;

	b.lsb = 1;
	b.pad = 0;
	b.msb = 1;

	printf("lsb =%u\n", b.lsb);
	printf("pad =%u\n", b.pad);
	printf("msb =%u\n", b.msb);

	if (b.msb == 1)
		printf("msb is 1\n");
	if (b.msb)
		printf("msb is true\n");

	return 0;
}
```

**Comment by jmr** [comment] 2020-11-14 11:52
I haven't had time to look in detail, but `unsigned x = b.msb; printf (..., x);` seems to work, so you have a work-around.

**Comment by jmr** [comment] 2020-11-15 09:18
Something related to varargs, but it doesn't always fail with varargs. See test cases in #1334.

**Comment by greg-king5** [comment] 2020-11-15 11:39
"msb-test.c":
```c
#include <stdio.h>

static const struct bitfield {
    unsigned int lsb: 1;
    unsigned int pad: 14;
    unsigned int msb: 1;
} b = {1, 0, 1};

static unsigned v;

int main(void)
{
    printf("b.lsb = %u\n", b.lsb);
    printf("b.pad = %u\n", b.pad);
    printf("b.msb = %u\n\n", b.msb);

    // This stops the printf()'s return value
    // from tricking the if () test into succeeding.
    v = 0x1234;

    if (b.msb == 1)
        printf("b.msb is 1.\n");

    if (b.msb)
        printf("b.msb is true.\n");

    v = 0x1234;
    return b.msb;
}
```
```
$ cl65 -t sim6502 msb-test.c
$ sim65 msb-test
b.lsb = 1
b.pad = 0
b.msb = 21

b.msb is true.
```
The program returned an "error-code" of 37.

Here is some Assembly that shows the bad code generation:
```asm
;
; if (b.msb == 1)
;
        lda     _b+1
        jsr     shrax4  ; <- .X register has garbage!
        jsr     shrax3
        ldx     #$00
        cpx     #$00
        bne     L0003
        cmp     #$01    ; <- .A now has some garbage
L0003:  jsr     booleq
        jeq     L0002
```
The bit-field is accessed as UCHAR, but the right-shifts are UINT.

**Comment by jmr** [comment] 2020-11-15 17:22
The problem is that `g_asr` falls through to`CF_INT` even if `CF_CHAR | CF_FORCECHAR`. 

https://github.com/cc65/cc65/blob/master/src/cc65/codegen.c#L4516
https://github.com/cc65/cc65/blob/master/src/cc65/codegen.c#L3129

So `CF_FORCECHAR` is more like `CF_MAYBECHARPLEASE` and I should make sure `X == 0` before calling any `CF_FORCECHAR` codegen?

**Comment by greg-king5** [comment] 2020-11-15 20:44
> So ... I should make sure `.X == 0` before calling any `CF_FORCECHAR` codegen?

It should be done by the code generators that care about `CF_FORCECHAR`, and only where the high byte affects the value that's put into the low byte.  For example, it matters in right shifts, but not left shifts.

**Comment by greg-king5** [comment] 2020-11-15 20:51
This bit-field issue is fixed by commit 2915464667e3098478f94d1a7b46e88f4fa8c6b5.

**Comment by jmr** [comment] 2020-11-15 21:10
Thanks!

**Closed** 2020-11-15 21:24 UTC
Labels: bug

**Comment by mzattera** [comment] 2020-11-19 21:17
Thanks for the unbelievably fast reply and fix!
