### ISSUE TITLE
XOR on Bitfield overwrites multiple bits

### ISSUE THREAD

**Issue by mhughson** [cc65/cc65#1465] opened 2021-04-17 04:16 UTC
**cc65.exe V2.18 - Git dc4142e**

I'm not totally sure if this is bug, but it seemed wrong.
I have a struct using bitfields:
```c
typedef struct player_object_data
{
	unsigned char is_cur_player:1;
	unsigned char is_clone:1;
	unsigned char is_wiz:1;
	unsigned char is_mirror:1;
	unsigned char facing_left:1;
} player_object_data;
```
With facing_left field, along with some others, set to 1, at some point in the program, I call:

`player_data.facing_left ^= 1;`

The result is that `facing_left` becomes 0, as expected, but so does every other field in the struct, which should have been unaffected.

-- 

NOTE: I simplified the code quite a bit, which may hide the actual bug. If that is the case, let me know; and, I can provide much larger piece of source.

**Comment by mrdudz** [comment] 2021-04-17 13:03
Most helpful would be a minimal program that can be compiled and then shows the bug

**Comment by acqn** [comment] 2021-04-17 14:03
'^=' is one of '@='s that are broken as reported in Issue #1462.

**Comment by mrdudz** [comment] 2021-05-24 11:17
should we close this as a duplicate of #1462 ?

**Comment by oliverschmidt** [comment] 2021-05-24 18:14
Based on @acqn's comment https://github.com/cc65/cc65/issues/1465#issuecomment-821827705 I think so.

**Closed by oliverschmidt** 2021-05-24 18:14 UTC
Labels: bug
