### ISSUE TITLE
cc65: Passing structs by value does not work (regression)

### ISSUE THREAD

**Issue by kugelfuhr** [cc65/cc65#2079] opened 2023-05-03 12:12 UTC
(shaking my head and rolling my eyes :-)

The following code:

```C
struct foo { int x; int y; int z; };

int f(struct foo foo)
{
    return foo.z;
}

int g(void)
{
    struct foo foo = { 1, 2, 3 };
    return f(foo);
}
```

is standard compliant C code that compiled & worked until about 20 minutes ago.

Since the merge of #2072 it does no longer work but generates "Passing 'struct foo' of this size by value is not supported" instead.

**Comment by mrdudz** [comment] 2023-05-03 12:22
Haha, funky :) Always suprising what the tests do not catch yet. @bbbradsmith please have a look :)

**Comment by mrdudz** [comment] 2023-05-03 12:38
reverted #2072 - the above program should probably be added as a test :)

**Comment by bbbradsmith** [comment] 2023-05-03 17:09
No, I don't feel this is fair to categorize as a regression or a bug, and the way you have reported this is antagonistic and pedantic. Please do not treat my efforts this way.

#2072 fixes a **critical** issue **you** yourself identified in #2022, and the removed support for passing a 3 byte struct was necessary to fix this more critical issue.

The 3-byte struct return code generation has the critical flaw you identified. My assessment of the situation is that the 3-bit struct by value code paths were not adequately implemented and must be thoroughly reviewed before either of them can be re-instated.

Silently overwriting memory #2022 a critical bug. Not being able to pass 3 byte structs specifically is not a bug. "Standard compliant" is very much not the issue here. 

cc65 has never supported structs by value of any size other than 1, 2, 3 or 4 bytes. Structs of size 5, 6, 7... these also don't work. cc65 has **always** been [documented as explicitly not standards compliant](https://cc65.github.io/doc/cc65.html#s4) in this respect.

I actually updated the documentation in #2072 to be explicitly clear about which struct sizes are actually an exception to this rule. You've chosen to revert this, and go back to the docs that erroneously say no structs by value are supported.

This is a **feature request**, not a regression or a bug. We want to _add_ support for 3 byte structs to cc65, and that is a very valid thing to want, and I support it having an issue to document the need/want for it.

But the way you have done this is _not_ the way to go about it.

**Comment by bbbradsmith** [comment] 2023-05-03 17:19
To clarify, I am very much for the goal of supporting 3-byte struct passing. However, it wasn't properly implemented before, and fixing it will take time and care. Going back to the broken implementation doesn't help.

The issue of #2022 is a severe problem that cannot be ignored. We should close this hole allowing unsafe code as soon as possible, and that's what #2072 does, in the least invasive way I could come up with.

I don't feel it's right to withhold that critical issue because you want a more perfect solution that supports everything. In the short term it should be disabled. In the long term we should have both, and we can. I just think the past to this looks like:

1. #2072 disable the currently unsafe broken implementation of it. Also document that heretofore undocumented abilities/limitations of cc65 struct passing.
2. Thoroughly review the 3-byte pass by value path and ensure it will produce safe and error free code, revise if necessary and enable this feature.
3. Thoroughly review the 3-byte return by value path and fix the cases where it produces broken code, then enable this feature.
4. Larger structs?

**Comment by mrdudz** [comment] 2023-05-03 17:27
Uhm, but the above struct isnt 3 bytes... its 6 bytes? Or am i missing something?

**Comment by bbbradsmith** [comment] 2023-05-03 17:33
That was a typo, the ints should be chars. A 6-byte struct by value has always been rejected by cc65. #2072 only removed the 3-byte struct support specifically.

**Comment by kugelfuhr** [comment] 2023-05-03 17:38
I'm sorry if you got the impression that I was criticizing your changes in an unethical way. This was in no way intended by me.

I was about to write above text into your PR and noticed that it was already merged by @mrdudz. The obvious haste was the reason for my "(shaking my head and rolling my eyes :-)" comment. Please accept my apologies for being unclear.

Regarding this issue: Passing structs **of any size** as parameters worked in version 2.18. It was broken for size=3 in  9f67b45ea0abd003a42b241d86bc763ef51b60bc and 66ecc0e52cc61e5969efc22c0045a739c7f6f9f3. The code shown above is **not** a typo. Just can compile it with cc65 2.18 or 2.19 and look at the generated assembly.

After your change, passing structs does no longer work for any size > 4. This is clearly a regression. I agree completely with you that the bug regarding return of 3 byte structs is serious and has to be fixed. But a fix that removes a previously working feature is not a good idea and should get revised. 

As said above, this comment would have gone into the PR but it was already merged and closed when I tried to do so.

Let me again say that I'm sorry. It was never my intention to upset you. But the bug report above is real and should be addressed.

**Comment by bbbradsmith** [comment] 2023-05-03 17:58
> I was about to write above text into your PR and noticed that it was already merged by @mrdudz. The obvious haste was the reason for my "(shaking my head and rolling my eyes :-)" comment. Please accept my apologies for being unclear.
I see. Yes, I didn't expect the PR to be merged quite so quickly, though I didn't expect it to be controversial either.

> After your change, passing structs does no longer work for any size > 4.
This is incorrect. Before #2072 structs of size > 4 were not allowed. My PR did not affect this. It may have worked in 2.19 but structs > 4 have probably been unsupported for years. Though as discussed, because of the lack of documentation it was surprising that they were ever supported.

> I agree completely with you that the bug regarding return of 3 byte structs is serious and has to be fixed. But a fix that removes a previously working feature is not a good idea and should get revised.
Since it's only removing 3-byte structs, I think it's worth doing in stages. First fix the critical issue with 3, so that the silent code corruption isn't hanging around until one of us has enough time and clarity to do the more complicated thing of making the rest work.

**Comment by mrdudz** [comment] 2023-05-03 18:00
Oh dear =) I was just going to add a test like the above - and it failed (of course) even before i even pulled the recent changes.

So we both were a bit too hasty and wrong. So before i go on..... i should revert the revert and again merge #2072, right? :) @kugelfuhr  @bbbradsmith

**Comment by kugelfuhr** [comment] 2023-05-03 18:29
Trying to be more careful this time but yes, the revert can be reverted. Sorry for the confusion.

 I've even tested struct assignment which was also broken before and works now by using `memcpy()`:

```C
struct foo { char a; char b; char c; };
struct foo foo, bar;
void f(void)
{
    foo = bar;
}
```

had previously the same problem as the struct return, it used eax and overwrote an additional byte. When applying #2072 it will use `memcpy()` and works therefore. It might be an idea to add this to the test.

**Comment by mrdudz** [comment] 2023-05-29 15:21
i am closing this ticket... @bbbradsmith please open new tickets (one per issue) for the other things you stumble(d) about

**Closed by mrdudz** 2023-05-29 15:21 UTC
Labels: bug, cc65

**Comment by bbbradsmith** [comment] 2023-05-29 17:46
I do think this issue was valid, at the very least as a feature request.

I don't know that it's a bug since the ability to pass large structs was never documented during the time where it worked, but I do agree with kugelfuhr that it can be considered a regression. The point of regression was incorrectly identified, as it was not due to #2072, but a long time earlier.

So, recreated as #2127 with the hope that it's clearer.

**Comment by mrdudz** [comment] 2023-05-29 17:59
> I do think this issue was valid, at the very least as a feature request.
> 
> I don't know that it's a bug since the ability to pass large structs was never documented during the time where it worked, but I do agree with kugelfuhr that it can be considered a regression. The point of regression was incorrectly identified, as it was not due to #2072, but a long time earlier.
> 
> So, recreated as #2127 with the hope that it's clearer.

Thanks you, clearer indeed!
