### ISSUE TITLE
[bug] Shifts by zero bits are broken

### ISSUE THREAD

**Issue by Fabrizio-Caruso** [cc65/cc65#1941] opened 2022-12-06 00:04 UTC
I am assuming that right-shifing an unsigned char should have no effect on an unsigned char. This is the case in my code when compiled with any compiler except CC65.

I have this macro:
```
#define initial_letter_drop() \
do \
{ \
    uint8_t i; \
    uint8_t k; \
    \
    _XL_PRINTD(0,1,3,(uint8_t) MIN_INITIAL_DROP + (level>>0)); \
    k = MIN_INITIAL_DROP + (level>>0); \
    _XL_WAIT_FOR_INPUT(); \
    for(i=0;i<(uint8_t) MIN_INITIAL_DROP + (level>>0);++i) \
    { \
        drop_letter(); \
        short_pause(); \
    } \
} while(0)
```
It produces a infinite loop when compiled with CC65. It can be fixed if I use `k` instead of `(uint8_t) MIN_INITIAL_DROP + (level>>0)`.

I will try to reproduce it with a minimal example.

Has any recent commit changed how the right shift operator works?

**Comment by mrdudz** [comment] 2022-12-06 00:21
> Has any recent commit changed how the right shift operator works?

I think so. Perhaps the test is missing a zero shift? :) What does the generated code look like?

**Comment by Fabrizio-Caruso** [comment] 2022-12-06 12:09
The problem is `>>0` which breaks the loop (it loops forever). Maybe it is an operator priority. I am still working on a minimal example.
The code is correctly compiled by other compilers. So I think this is a bug.

**Comment by mrdudz** [comment] 2022-12-06 12:17
I got that much - hence the question about how the generated code looks like :)

**Comment by Fabrizio-Caruso** [comment] 2022-12-06 23:31
@mrdudz 
Minimal tiny broken case (loops forever but should only loop twice):
```
#include <stdio.h>
#include <stdint.h>

uint8_t foo;
uint8_t bar; // Without this there is no bug

int main(void)
{            
    uint8_t i; 

    foo = 1U;
    bar = 3U;  // Without this there is no bug

    for(i=0;i<(uint8_t) 1U + (foo>>0);++i)
    {
        printf("foo\n");
    }

    printf("OK");

    return 0;
}
```

The bug appears independently of `-O` and `-Cl`.
Moreover this was broken even if I use a snapshot from the 4th of April.
So it is not very recent.

**Comment by acqn** [comment] 2022-12-07 16:07
```asm
;
; for (i = 0; i < foo >> 0; ++i)
;
	ldx     #$00
	lda     #$00
	ldy     #$00
	sta     (sp),y
L0002:	ldy     #$00
	ldx     #$00
	lda     (sp),y
	jsr     pushax
	lda     _foo
	ldx     _foo+1 ; Should be ldx #$00
	jsr     tosltax
	jne     L0005
	jmp     L0003

```

**Comment by Fabrizio-Caruso** [comment] 2022-12-07 17:35
@mrdudz @acqn There are two problems:
1: big problem: the produced Assembly is wrong
2: small problem: >>0 should be elided by the optimizer.

Obviously a fix for the small problem would hide the bigger bug. IMHO it is therefore important to solve the bigger problem first.

**Comment by laubzega** [comment] 2022-12-07 22:20
In an ironic twist, the compiler makes the mistake leading to problem number 1 while solving problem 2. ;)

I have a simple patch that passes built-in tests, but I need to think about its implications - specifically, if not following integer promotion rules for uint8_t >> 0 (i.e. not promoting the result to uint16_t) could lead to other problems. I think it should not, but...

**Comment by Fabrizio-Caruso** [comment] 2022-12-07 22:22
@acqn So if both 1. and 2. issues are fixed the good code should not have a call to any shift routine. May be some trivial rules should simply >>0 into an empty string even before it goes to the compiler... I don't know if it is possible in general...

**Comment by laubzega** [comment] 2022-12-07 22:44
I would also change the title to "Shifting by literal of zero bits is broken". Because left shift has the same issue.

Minimal testcase:


```
#include <stdio.h>
#include <stdint.h>

uint8_t foo=1U;
uint8_t bar=3U; // You need it to reproduce the issue

int main(void)
{            
    printf(foo == foo << 0 ? "OK\n" : "FAIL\n");
    return 0;
}
```

**Comment by acqn** [comment] 2022-12-08 15:11
> I have a simple patch that passes built-in tests, but I need to think about its implications - specifically, if not following integer promotion rules for uint8_t >> 0 (i.e. not promoting the result to uint16_t) could lead to other problems. I think it should not, but...

The rules shall always be followed even we are shifting by 0.

**Comment by spiro-trikaliotis** [comment] 2022-12-08 15:19
> The rules shall always be followed even we are shifting by 0.

You mean the integer promotion rules, in order to be standards compliant?

If yes: No, the correct sentence is: "The behaviour shall always be AS IF the rules were followed".
The C standard specifically has this "as if" clause. If the implementation can guarantee that not following the rules (or following other rules) has the same effect as if the rules were followed, it is ok.

Thus,  if a shift left or right were completely ignored, and the outcome were the same as if the integer promotion was done, then it would be fine to ignore the shift, without doing integer promotion.

Note that I do not know if the behaviour is the same; I only spoke about the hypothetical possibility!

**Comment by laubzega** [comment] 2022-12-08 18:09
Looks like @acqn has a fix that keeps the promotion in place.

**Comment by polluks2** [comment] 2022-12-08 19:32
> You mean the integer promotion rules, in order to be standards compliant?
> 
> If yes: No, the correct sentence is: "The behaviour shall always be AS IF the rules were followed". The C standard specifically has this "as if" clause. If the implementation can guarantee that not following the rules (or following other rules) has the same effect as if the rules were followed, it is ok.
> 
> Thus, if a shift left or right were completely ignored, and the outcome were the same as if the integer promotion was done, then it would be fine to ignore the shift, without doing integer promotion.
> 
> Note that I do not know if the behaviour is the same; I only spoke about the hypothetical possibility!

This makes sense, integer promotion shall make your life easier. If it causes the problem, drop it :-)

**Comment by acqn** [comment] 2022-12-09 15:33
cc65 always promotes `char`s to `int`s when loading them unless _extra care_ is taken to avoid that while keeping the behaviour correct.

The assertion would fail without the promotion:
```c
char foo;
_Static_assert (sizeof (foo >> 0) == sizeof (int), "Result type of (foo >> 0) should be int");
```

**Comment by Fabrizio-Caruso** [comment] 2022-12-09 18:05
The promotion alone does not seem to be the cause of the problem.
The following code is correctly compiled:
```
uint8_t foo;
uint8_t bar; // Without this there is no bug

int main(void)
{
    uint8_t i;

    foo = 1U;
    bar = 3U;  // Without this there is no bug

    for(i=0;i<(int16_t) foo;++i)
    {
        printf("foo\n");
    }

    printf("OK");

    return 0;
}
```

**Comment by laubzega** [comment] 2022-12-09 18:49
@Fabrizio-Caruso No, the problem is the promotion of the value shifted by the literal (i.e. not variable) zero bits. As it is now, the compiler first promotes the result from byte to int, and right after that decides there is no code to emit, since shift by zero does not change the value in any way. However, the result type was determined to be int, so future references to it (like the one that loop range check does) reach for a 16-bit value, despite there only being a single underlying byte. So the range check in your original code sees 3*256+1=769 rather than 1 and thus loops infinitely. This also means that the comment "Without this there is no bug" is actually incorrect. Bug is there at all times, it's just that "bar = 3" makes it fail deterministically.

**Comment by mrdudz** [comment] 2022-12-10 00:06
Mmmh perhaps that test @acqn  posted could be added to the testprog in #1943 ? (I will look at it this weekend...)

**Comment by mrdudz** [comment] 2023-01-28 11:35
@Fabrizio-Caruso i made a new PR from the fix acqn provided in his repo in #1983 - please check/confirm

**Comment by mrdudz** [comment] 2023-02-09 14:05
@Fabrizio-Caruso please? :)

**Comment by Fabrizio-Caruso** [comment] 2023-02-09 21:57
@mrdudz Sorry for my late reply. The test case I have posted above, is correctly compiled a recent version of cl65.exe
```
$ cl65.exe --version
cl65.exe V2.19 - Git e944a30
```

**Comment by mrdudz** [comment] 2023-02-09 22:06
Cool, so we can close this :)

**Closed by mrdudz** 2023-02-09 22:06 UTC
Labels: bug, cc65

**Comment by laubzega** [comment] 2023-02-12 22:15
Apologies, I was traveling longer than expected. Things look fine, thank you @mrdudz for handling this!
