### ISSUE TITLE
`.define` doesn't respect parentheses scoping

### ISSUE THREAD

**Issue by nrivard** [cc65/cc65#1384] opened 2021-01-15 11:49 UTC
`.define` doesn't seem to respect parentheses scoping. My reading of the documentation is that this is more of a straight substitution than `.macro` which is intended for blocks of instructions.

My use case is I have some size constants:
```
VERA_size_32 = 0
VERA_size_64 = 1
VERA_size_128 = 2
VERA_size_256 = 3
```

A memory location has both a height (masked by %1100000) and a width (masked by %0011000). They use the same values, so I create some `.define`s to simplify this:
```
.define VERALayerWidth(width)    (width << 4)
.define VERALayerHeight(height) (height << 6)
```

But now when I try to use them, I get assembler errors about the storage size being far too large. Observe:
```
LDA #(VERALayerWidth(VERA_size_128) | (VERALayerHeight(VERA_size_64))
```
This fails with:
```
source/main.asm(40): Error: Range error (2112 not in [0..255])
make: *** [all] Error 1
```

If I manually replace one of them, and _prepend_ it, it works:
```
LDA #($60 | VERALayerWidth(VERA_size_128))
```
If I reverse this, it fails:
```
LDA #(VERALayerWidth(VERA_size_128) | $60)
```

Am I using this feature wrong? If so, is there a feature that does this? I have tons of cases where stuff is duplicated otherwise. Imagine 2 VIAs, same registers, etc. just differentiated by some base address. Would be nice to have just pass the base address and have it offset by a substitution function.

**Comment by mrdudz** [comment] 2021-05-24 09:56
a workaround could be to add the "lowbyte" operator to those defines, ie
```
.define VERALayerWidth(width)    (<(width << 4))
.define VERALayerHeight(height) (<(height << 6))
```

**Comment by nrivard** [comment] 2021-05-24 11:11
That workaround doesn't work. I still get the same issue. Also tried:
```
.define VERALayerWidth(width)   ($FF & (width << 4))
.define VERALayerHeight(height)   ($FF & (height << 6))
```
The issue still occurs when i try to OR them together. Unfortunately, that's the entire point of this bug :)

**Comment by mrdudz** [comment] 2021-05-24 11:15
now that is interesting... too bad

**Comment by kugelfuhr** [comment] 2023-03-29 19:22
Not sure if this is still of any relevance, but I stumbled over it, so the following may be helpful:

The problem is that the macros aren't used as intended. Please [see the docs](https://cc65.github.io/doc/ca65.html#ss12.7). The relevant part is:

>Note that, while formal parameters have to be placed in parentheses, the actual argument used when invoking the macro should not be. The invoked arguments are separated by commas only; if parentheses are used by accident, they will become part of the replaced token.
>
>If you wish to have an expression follow the macro invocation, the last parameter can be enclosed in curly braces {} to indicate the end of that argument.

So what happens is that all of the tokens following `LDA #(VERALayerWidth` are passed as arguments to the macro which then won't work as expected.

The solution is also in the docs: First, don't enclose the parameters in parenthesis. Next, enclose them in curly braces instead, to mark beginning and end of the arguments. The code will still be readable this way. The following works:

```
        LDA     #VERALayerWidth{VERA_size_128} | VERALayerHeight{VERA_size_64}
```

You may also add parenthesis around the expression if you like:

```
        LDA     #(VERALayerWidth{VERA_size_128} | VERALayerHeight{VERA_size_64})
```

**Comment by bbbradsmith** [comment] 2023-05-03 06:29
For the reason given by kugelfuhr above this probably shouldn't be tagged as a bug, though I do agree the way parentheses work in ca65 macros is very surprising. I tried to help improve the documentation of that in the past, but they're pretty unusual in how they work and unfortunately I don't have any good suggestions about how to make it easier.

**Comment by mrdudz** [comment] 2023-05-03 11:34
I agree, suprising, but works as advertised. closing :)

**Closed by mrdudz** 2023-05-03 11:34 UTC
Labels: bug, ca65
