### ISSUE TITLE
How to assign c128.lib to a user-defined segment instead of CODE?

### ISSUE THREAD

**Issue by Fabrizio-Caruso** [cc65/cc65#893] opened 2019-05-12 21:25 UTC
In https://github.com/Fabrizio-Caruso/C64_Multiplexer_C_LIB/blob/master/cfg/c128_multiplexer_sid_at_2400_gfx_at_3000.cfg
I have defined the two code segments CODE and CODE2
Code memory is split in 
- a small EXTRA area at $1C0D-$23FF and 
- a big MAIN area starting at $4000

How can I have all the generated code including c128.lib to go to MAIN except for the STARTUP and an interrupt routines defined in an Assembly file?

I have set up the segments as follows:
```
SEGMENTS {
    ZEROPAGE: load = ZP,       type = zp;
    LOADADDR: load = LOADADDR, type = ro;
    EXEHDR:   load = HEADER,   type = ro;
    STARTUP:  load = EXTRA,    type = ro;
    LOWCODE:  load = MAIN,     type = ro,  optional = yes;
    ONCE:     load = MAIN,     type = ro,  optional = yes;
    CODE:     load = EXTRA,    type = ro;
    CODE2:    load = MAIN,     type = ro;
    SID:      load = SID,      type = ro;
    RODATA:   load = MAIN,     type = ro;
    DATA:     load = MAIN,     type = rw;
    INIT:     load = MAIN,     type = bss;
    GFX:      load = GFX,      type = rw;    
    BSS:      load = MAIN,     type = bss, define   = yes;
}
```
and I compile with:
```
sin_scroller_music_c128:
	$(CC65_PATH)$(MYCL65) $(MYC128CCFLAGS) $(MYSIDC128CFG) -v -m map.txt \
	--asm-define MAXSPR=16 \
	--asm-define FAST_MODE=1 \
	--asm-define MUSIC_CODE=1 \
	$(SID_PATH)/sid_at_2400.s \
	--code-name CODE \
	$(SOURCE_PATH)/multi_ca65_split.s \
	--code-name CODE2 \
	$(SOURCE_PATH)/sin_scroller.c \
    $(GRAPHICS_PATH)/graphics.s \
	-o $(BUILD_PATH)/sin_scroller_music_c128.prg
```
but the small EXTRA are gets an overflow... It seems that c128.lib is put there.
How can I avoid this?

In the map file I see:
```
...
C:\cc65-snapshot-win32/lib/c128.lib(_printf.o):
    CODE              Offs=0002B0  Size=0003A5  Align=00001  Fill=0000
    BSS               Offs=000007  Size=00002B  Align=00001  Fill=0000
    DATA              Offs=000000  Size=000003  Align=00001  Fill=0000
C:\cc65-snapshot-win32/lib/c128.lib(add.o):
    CODE              Offs=000655  Size=00001C  Align=00001  Fill=0000
C:\cc65-snapshot-win32/lib/c128.lib(addysp.o):
    CODE              Offs=000671  Size=00000E  Align=00001  Fill=0000
C:\cc65-snapshot-win32/lib/c128.lib(axlong.o):
    CODE              Offs=00067F  Size=00000D  Align=00001  Fill=0000
C:\cc65-snapshot-win32/lib/c128.lib(callmain.o):
    CODE              Offs=00068C  Size=000017  Align=00001  Fill=0000
    DATA              Offs=000003  Size=000004  Align=00001  Fill=0000
C:\cc65-snapshot-win32/lib/c128.lib(clrscr.o):
...
```

**Comment by oliverschmidt** [comment] 2019-05-13 05:32
You have to put the cart before the horse ;-)

The name of the segment used for code (and in fact for the other "things" too) is defined during compile/assemble time. The memory area a segment "goes into" is defined during link time.

The library is already complied/assembled so you can't change the segment used for code anymore. It stays `CODE`. But you can freely define in which memory area the CODE segment goes.

You assemble/compile your own source so you can define the segment used for code here with command-line-options/directives/pragmas.

So the overall idea is to design your linker config "around" the library. Decide where you want it to go and name the segments accordingly.

Two examples how I personally have certain project source files use a non-standard code segment:
https://github.com/oliverschmidt/contiki/blob/master/platform/apple2enh/Makefile.apple2enh#L48-L56
https://github.com/oliverschmidt/contiki/blob/master/platform/atarixl/Makefile.atarixl#L43-L48

**Comment by greg-king5** [comment] 2019-05-13 07:48
The problem is that you swapped two things: memory areas and segments.  But, the two swaps cancel each other!
- Don't swap the segments: `CODE:` should continue to load into `MAIN`; `CODE2:` should load into `EXTRA`.  `CODE2:` must be marked as optional.
- Load `LOWCODE:` into `EXTRA`.
- `--code-name` is a compiler option; it affects only C files.  Only your Assembly source files can tell ca65 where to put their code.
  - Don't use `--code-name` in that make-file recipe.
- Put your sprite handler (interrupt) code into `.segment "LOWCODE"`.

**Comment by Fabrizio-Caruso** [comment] 2019-05-21 06:31
Thanks! I will have to change lots of things.
My mistake was to assume the --code-name had an effect on an Assembly file.
What does LOWCODE mean? Code meant to go to the first 16k of RAM?

**Comment by oliverschmidt** [comment] 2019-05-21 08:12
> What does LOWCODE mean? Code meant to go to the first 16k of RAM?

The term LOWCODE is suboptimal. It should rather read SAFECODE. It's supposed to have an abstract cross-target meaning: Code residing here can be reached regardless of memory banking.

This is interesting in the context of interrupts but not limited to interrupts. Low level interrupt handlers tend to "normalize" some memory banking settings before calling high level interrupt handlers. And if cc65 interrupts are used then both the cc65 interrupt support code as well as the user level interrupt code run in this "normalized" environment (which may differ from the "optimized" environment the cc65 startup code sets up). All code supposed to be reachable from the "normalized" environment needs to go into LOWCODE.

**Closed** 2019-05-30 18:26 UTC
Labels: question
