### ISSUE TITLE
Problem with static locals?

### ISSUE THREAD

**Issue by IrgendwerA8** [cc65/cc65#1108] opened 2020-07-20 08:35 UTC
Maybe I'm missing something (at least it's Monday), but the following code prints only "0" for "cx" while I think it shouldn't:

```
#include <stdio.h>

unsigned char x=0;

void
PrintVar(void)
{
	unsigned char cx = x+1;
	printf("cx: %d\n", cx);
}


void
main(void)
{
	do
	{
		++x;
		PrintVar();
	}
	while(1);
}
```

Executable created only with the "-Cl" option. Without it, it works ok.

**Comment by mrdudz** [comment] 2020-07-20 10:33
Did it work in earlier builds?

**Comment by mrdudz** [comment] 2020-07-20 10:37
@oliverschmidt how would we add this as a test case? it's not practical to add static locals to the options being tested for all tests, right? "misc" and special case rule?

**Comment by mrdudz** [comment] 2020-07-20 11:06
If you move the assignment into a seperate line, then it works as expected. I guess the compiler somehow gets confused by it not being constant.

**Comment by IrgendwerA8** [comment] 2020-07-20 11:10
> Did it work in earlier builds?

This is the commit, which breaks the code:

**Comment by mrdudz** [comment] 2020-07-20 11:39
@acqn HELP! :)

**Comment by acqn** [comment] 2020-07-20 12:12
I'll take a look.

**Comment by mrdudz** [comment] 2020-07-20 12:31
It's short for --static-locals ... all local variables turn into static variables (so they dont live in the local stack frame, which speeds up things a lot)

**Comment by oliverschmidt** [comment] 2020-07-20 12:42
> @oliverschmidt how would we add this as a test case? it's not practical to add static locals to the options being tested for all tests, right? "misc" and special case rule?

How about using #pragma static-locals ([push,] on|off) - https://cc65.github.io/doc/cc65.html#ss7.16 ?

**Comment by acqn** [comment] 2020-07-20 12:45
It takes more time to figure out how to push a branch to GitHub than to fix this....

**Comment by oliverschmidt** [comment] 2020-07-20 12:52
Maybe this is all totally obvious to you and/or maybe I'm missing the point, but just in case:

Git branches are super-cheap. So the general idea is to have a separate Git branch for everything intended to become a GitHub pull request. After creating the GitHub pull request further commits pushed to the respective Git branch show up automatically in the pull request. After the pull request is merged the respective Git branch is to be deleted.

**Comment by acqn** [comment] 2020-07-20 13:02
> 
> 
> > it's not practical to add static locals to the options being tested for all tests, right? "misc" and special case rule?
> 
> How about using #pragma static-locals ([push,] on|off) - https://cc65.github.io/doc/cc65.html#ss7.16 ?

In my opinion, there's no need to do that. All needed to test code generation with `-Cl` is to check all the part where it can do differently from real `static` variables, and anything more would be duplicate. A "unit test" dedicated to it may be enough.

**Comment by oliverschmidt** [comment] 2020-07-20 13:05
@acqn: Unfortunately I don't understand at all what you want to express. Don't we agree that static locals need to be active to trigger the bug in question? My comment was supposed to show how to activate static locals without modifying Makefiles.

**Comment by acqn** [comment] 2020-07-20 13:19
> 
> 
> @acqn: Unfortunately I don't understand at all what you want to express. Don't we agree that static locals need to be active to trigger the bug in question? My comment was supposed to show how to activate static locals without modifying Makefiles.

I see. Agreed. Perhaps I missed why you suggested using #pragma.

**Comment by mrdudz** [comment] 2020-07-20 13:35
Yeah i didn't think of the pragma :) Will use that :)

**Comment by oliverschmidt** [comment] 2020-07-20 13:38
Great - and thanks in advance for the regression test. This issue is the perfect show case for their importance!

**Comment by oliverschmidt** [comment] 2020-07-20 13:40
@acqn: Thanks for the super-quick fix.

@mrdudz: Thanks for commiting to contribute a regression test. The missing test kept me from closing this issue...

**Closed by oliverschmidt** 2020-07-20 13:40 UTC
Labels: bug

**Comment by mrdudz** [comment] 2020-07-20 13:50
cheers :)
