### ISSUE TITLE
ld65: Precondition violated errors after optimizing two C64 programs

### ISSUE THREAD

**Issue by HarryPotterC-glitch** [cc65/cc65#2544] opened 2024-11-23 21:04 UTC
Hi!  I'm joseph Rose, a.k.a. Harry Potter, and recently, I've been getting the following error after optimizing two C64 programs:

ld65: Precondition violated: Index < C->Count, file 'common/coll.h', line 129

The C128 versions work fine.  Upgrading to the latest version of cc65 didn't help.

**Comment by mrdudz** [comment] 2024-11-23 21:08
Please provide a minimal test case to reproduce this problem

**Comment by HarryPotterC-glitch** [comment] 2024-11-23 21:23
I have as of yet been unable to reproduce the problem. I will continue to work on it for now.
    On Saturday, November 23, 2024 at 04:08:44 PM EST, Bob Andrews ***@***.***> wrote:  
 
 


Please provide a minimal test case to reproduce this problem

**Comment by HarryPotterC-glitch** [comment] 2024-11-23 21:25
If it helps, the compile command line is:
ld65 -o main.prg -C ..\Lib64\hide64.cfg c64_cfgd.o main.o color.o cclear.o bordercolor.o bytewordaccess.o cgetc.o getkey.o getkey2.o -( tmplib.lib ..\Fields\fields64.lib ..\Lib64\hidden64.lib c64.lib -)


    On Saturday, November 23, 2024 at 04:08:44 PM EST, Bob Andrews ***@***.***> wrote:  
 
 


Please provide a minimal test case to reproduce this problem

**Comment by HarryPotterC-glitch** [comment] 2024-12-03 00:04
I significantly narrowed down the bug: it happened when I converted a call to sprintf() to strcpy() and strcat().  I attached the before code:----------------------------------static unsigned char __fastcall__ openfile (char* s, unsigned char mode){ sprintf (fi, "@:%s,%c",s, filetypes[getent(tmpnum[nameref])->filetype][0]); return cbm_open2 (fi, mode);}
--------------------------------and after:--------------------------------static unsigned char __fastcall__ openfile (char* s, unsigned char mode){ // char c[2]; // c[0]=filetypes[getent(tmpnum[nameref])->filetype][0]; c[1]=0; // fi[0]=0; strcpy(fi, "@:"); strcat(fi, s); strcat(fi, ","); strcat(fi, &filetypes[getent(tmpnum[nameref])->filetype]); //strcat(fi, c); //Open the file. return cbm_open2 (fi, mode);}
-----------------------------and plan to finish the test case tomorrow morning.
    On Saturday, November 23, 2024 at 04:08:44 PM EST, Bob Andrews ***@***.***> wrote:  
 
 


Please provide a minimal test case to reproduce this problem

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: ***@***.***>
  

|  | Virus-free.www.avast.com |

**Comment by mrdudz** [comment] 2024-12-03 01:12
ugh jesus, IF you answer by email, please make sure it doesn't result in this mess.

And then, please attach a small program that we can compile to demonstrate the problem

**Comment by sidneycadot** [comment] 2024-12-29 22:03
Hi @HarryPotterC-glitch 

Please provide a working, self-contained, minimal program to reproduce the issue. Provide a CONCISE BUT COMPLETE description of how to compile and run it, what you'd expect the compiled program to do, and what the compiled program does that doesn't conform to your expectation.

Use the web interface for communication rather than email, to prevent mangling of inline code: https://github.com/cc65/cc65/issues/2544

Put any code between triple-backtick markers to ensure that it shows up as code in your message. Generally, it's useful to consult the Github Markdown guide to understand how to make messages that are easy to parse: https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax

Use the "Preview" tab before the "Comment" tab, to ensure your message is understandable, and the code you're discussing is laid out

The information you provided so far is not up to a standard that allows maintainers to understand and reproduce the issue you're seeing (or think you're seeing) with a minimal amount of effort, and that's really necessary.

**Comment by HarryPotterC-glitch** [comment] 2024-12-29 23:54
Switching the order of the libraries on the ld65 command line seems to have fixed the issue.  I'm sorry for not mentioning this earlier: I thought you weren't going to pursue the issue, and I didn't want to piss you off again for asking for help then discovering I didn't need it.

|  | Virus-free.www.avast.com |

**Comment by sidneycadot** [comment] 2024-12-30 07:06
Hi @HarryPotterC-glitch,

In the future please tell if a reported issue turns out to be a mistake. It happens a lot, and it's always better to close the issue than to leave it dangling.

Closing the issue.

**Closed by sidneycadot** 2024-12-30 07:06 UTC

**Comment by HarryPotterC-glitch** [comment] 2024-12-30 11:41
I'm sorry.  :(  I sometimes don't know what I'm doing.
Message ID: ***@***.***>
  

|  | Virus-free.www.avast.com |

**Comment by sidneycadot** [comment] 2024-12-30 12:28
No worries, we all make mistakes. The trick is to learn from them :)
