### ISSUE TITLE
Regression: "0 < i--" is optimized to "0 < --i".

### ISSUE THREAD

**Issue by vrubleg** [cc65/cc65#784] opened 2018-10-20 09:58 UTC
I have tried to build “[Sir Ababol](http://www.mojontwins.com/juegos_mojonos/sir-ababol-nes/)” using the latest version of cc65. For some reason, it had a very glitchy title screen. I have investigated it a bit, and it turned out that the issue is in this function:
```c
void __fastcall__ un_rle_screen (unsigned char *rle) {
	wx = 0; wy = 0; i = 0;
	while (i < 240) {
		t = (*rle);
		rle ++;
		if (t & 128) {
			top = t & 127;
			t = (*rle);
			rle ++;
			while (0 < top--) {
				draw_tile (wx, wy, t);
				wx = (wx + 2) & 31; if (!wx) wy += 2;
				i ++;
			}
		} else {
			draw_tile (wx, wy, t);
			wx = (wx + 2) & 31; if (!wx) wy +=2;
			i ++;
		}
	}
	// 64 attributes
	i = 64; gp_addr = 0x23c0;
	while (0 < i--) {
		vram_adr (gp_addr++);
		vram_put (*rle++);
	}
}
```
Just look at this part of generated assembly:
```Assembly
;
; while (0 < top--) {
;
L330D:	lda     #$00
	dec     _top
	cmp     _top
	bcc     L330B
;
; } else {
;
	jmp     L3B6B
```
It decrements `_top`; and only then, it does the comparison. But, it should do comparison first; and only then, it should decrement `_top`. I have replaced it to this code:
```Assembly
L330D:
	lda _top
	dec _top
	cmp #$00
	beq L3B68
	bcs L330B
	jmp L3B68
```
And now, it works as expected.

Old cc65 had generated this monstrous code:
```Assembly
;
; while (0 < top--) {
;
L330D:	jsr     push0
	lda     _top
	pha
	sec
	sbc     #$01
	sta     _top
	pla
	jsr     tosicmp0
	bcc     L330B
;
; } else {
;
	jmp     L3B6B
```
It seems that someone had tried to add a great optimization, and forgot to take into account the difference between `--i` and `i--`. It would be really nice to preserve the optimization, but to do it in a right way.

**Comment by oliverschmidt** [comment] 2018-10-22 18:37
First of all thanks for the analysis already done so far :-)

Could you additionally try to find the (close to) minimal code that triggers the bug? Usually that helps a lot when trying to find the issue.

**Comment by vrubleg** [comment] 2018-10-22 18:56
http://veg.by/files/temp/cc65-sirababol.7z

It's an adopted version of Sir Ababol source code which can be compiled using the latest cc65. Look at dev/compile.bat - you can set path to the compiler there.

Just compile the game, and you will see wrong code in the game.s, it is easy to find this part of code using search function of a text editor. This part of code has second `while (0 < i--)` at the end, and it is also compiled as `while (0 < --i)`. It seems it is not hard to reproduce. The bug is visible in the title screen of the game, so it is even convenient for testing. If the title screen is not glitchy, the bug is fixed.

**Comment by oliverschmidt** [comment] 2018-10-22 19:00
Just to make sure there's no misunderstanding: My previous comment was asking for something like the code in https://github.com/cc65/cc65/issues/735.

**Comment by vrubleg** [comment] 2018-10-25 08:28
Now, I'm busy with my project which uses ca65 solely. I'll provide a shorter example if it is still required later. But the game itself is not so huge. I had spent maybe just an hour to build it using the latest cc65 (I had to build new runtime.lib and fix some incompatibilities in the linker configuration file) and to find the cause of the issue with the title screen. The archive above includes all the required changes to build it using the latest cc65, so it is really not hard to build it and to check that the assembly in the game.s has the described issue.

**Comment by mrdudz** [comment] 2018-10-25 08:38
its still close to impossible to fix anything without a minimal testcase (and then the testcase will go into the regression tests, to make sure it wont break again)

**Comment by greg-king5** [comment] 2018-10-26 14:04
```c
static unsigned failure = 1;
static unsigned char count = 1;

int main(void)
{
    while (0 < count--) {
        --failure;
    }
    return failure;
}
```
The unoptimized program succeeds.  The optimized program fails.

**Comment by oliverschmidt** [comment] 2018-10-26 14:19
```c
static int failure = 1;
static unsigned char count = 1;

int main(void)
{
    while (0 < count--) {
        --failure;
    }
    return failure;
}
```

**That** simple? And none of the existing regression tests tests this? Wow!

**Comment by holmak** [comment] 2019-01-09 05:36
The error is introduced in the compiler pass "OptStackOps". I used a slightly simplified version of the test program posted by @oliverschmidt.

```
static unsigned char failure = 1;
static unsigned char count = 1;

int main(void)
{
    while (0 < count--)
    {
        --failure;
    }
    return failure;
}
```

Last good pass:

```
;
; while (0 < count--)
;
	jmp     L0006
;
; --failure;
;
L0004:	ldx     #$00
	dec     _failure
	lda     _failure
;
; while (0 < count--)
;
L0006:	ldx     #$00
	txa
	jsr     push0
	lda     _count
	dec     _count
	jsr     tosicmp0
	bcc     L0004
;
; return failure;
;
	ldx     #$00
	lda     _failure
;
; }
;
	rts
```

After `OptStackOps`:

```
;
; while (0 < count--)
;
	jmp     L0006
;
; --failure;
;
L000A:	dec     _failure
	lda     _failure
;
; while (0 < count--)
;
L0006:	ldx     #$00
	txa
	dec     _count
	cmp     _count
	bcc     L000A
;
; return failure;
;
	lda     _failure
;
; }
;
	rts
```

**Comment by acqn** [comment] 2020-01-01 03:39
Register usage isn't currently tracked correctly for OptStackOps transformations, which is the cause of this issue as well as #167. I'm working on an improved way to handle this.

**Comment by acqn** [comment] 2020-01-02 11:55
By disabling OptStackOps we'll be left with tosicmp0. While it's possible to make OptStackOps correctly support optimizing such code (generally using php/plp?), it might be helpful to add a new OptIntCmp or something to optimize tosicmp0 out as it seems to be common (eg. #292).

On the other hand, it makes me wonder why we are using int16_t for boolean everywhere in the first place and then try to optimize them out later. In the C standard bool is int, but seriously, what storage we really need for such "explicit boolean usage" is just 1 bit (1 = true, 0 = false). Why can't we just hold the bit in a byte and convert it to int only when necessary?

**Comment by oliverschmidt** [comment] 2020-06-22 21:29
Fixed with https://github.com/cc65/cc65/pull/1053.

**Closed by oliverschmidt** 2020-06-22 21:29 UTC
Labels: bug, help wanted

**Comment by vrubleg** [comment] 2020-06-22 22:23
I confirm that the Sir Ababol now can be built with the latest cc65, and it has working title screen.

**Comment by polluks** [comment] 2020-06-22 23:12
@oliverschmidt Do you agree? https://github.com/cc65/wiki/wiki/Roadmap#V219 :-)

**Comment by oliverschmidt** [comment] 2020-06-23 08:53
@polluks: Even after one night's sleep I still don't get the point :-(

To me it seems as if https://github.com/cc65/cc65/pull/1053 has already reached that goal, didn't it? So do you want to express that it's a pity that it took so long to just get "as good again" as cc65 has already been back then? Or do you want to express that I should add a v2.19 tag? Or <?>

**Comment by polluks** [comment] 2020-06-23 08:57
the latter

**Comment by vrubleg** [comment] 2020-06-23 08:59
Probably, it is worth to wait a bit, just in case if there are some other unexpected regressions, before claim it as a new released version.

**Comment by oliverschmidt** [comment] 2020-06-23 09:03
@polluks: I see :-) In general a good idea!

I suggest to see if https://github.com/cc65/cc65/pull/1055 and/or https://github.com/cc65/cc65/pull/1058 become ready for merging soon and go from there.
