### ISSUE TITLE
Possible bug in code optimization?

### ISSUE THREAD

**Issue by henriko-se** [cc65/cc65#971] opened 2019-11-07 20:22 UTC
I got into a problem using some portable third party library on the C64. It works if I don't use any optimization. But, it behaves very strange when having optimization enabled.

Managed to isolate the problem into the small test program below. Perhaps I would not write code like this myself, but I don't think there is anything in the code that is illegal, dangerous, or undefined.
```C
/*
 * test.c
 *
 * Small test program for demonstrating
 * a possible bug in the code optimization.
 *
 * When compiled using
 * > cl65 -t c64 -o test.d64 test.c
 * the result is the expected 00
 *
 * When compiled using
 * > cl65 -t c64 -O -o test.d64 test.c
 * the result is the unexpected EE
 *
 * > cl65 --version
 * cc65 V2.18 - Git 1d39863a
 * > cc65 --version
 * cc65 V2.18 - Git 1d39863a
 *
 * Used VICE to test, as this
 * > vice-jz.x64 -autostart test.d64
 */

#include <stdio.h>
#include <stdint.h>

uint16_t global;

static uint8_t unpredictable() {
    uint8_t result;
    uint16_t leftside = 0x0020u;
    uint16_t rightside = 0x0020u;

    global = leftside & rightside;

    if (global & (uint16_t)0xFFu)
    {
      result = 0x00u;
    }
    else
    {
      result = 0xEE;
    }

    return result;
}

void main(void)
{
  uint8_t zeroplease;
  zeroplease = unpredictable();

  printf("test of unpredictable results\n");
  printf("zero please: %02x\n", zeroplease);
}
```

**Comment by mrdudz** [comment] 2019-11-07 20:38
interesting... does it still break when using "static uint8_t unpredictable(void)" ?

**Comment by henriko-se** [comment] 2019-11-07 20:56
Good point. I missed miss that. But adding void in the function definition didn't dodge the problem. Still get the unexpected result when optimization is enabled.

**Comment by oliverschmidt** [comment] 2019-11-10 09:48
As expected this isn't related in any way to the C64:
```
>cl65 -t sim6502 test.c
>sim65 test
test of unpredictable results
zero please: 00
>cl65 -t sim6502 -O test.c
>sim65 test
test of unpredictable results
zero please: ee
```

**Comment by acqn** [comment] 2019-12-29 23:34
I think the issue is caused by a mistake in OptPushPop. It optimizes out PHA/PLA pairs followed by a STA but ignores later usage of N/Z changes caused by the PLA. A quick fix could be just to insert a LDA to reload the N/Z states from the STA'ed value in place of the removed PLA.

I can make a PR if this fix is OK.

**Comment by oliverschmidt** [comment] 2020-04-07 18:21
Fixed with https://github.com/cc65/cc65/pull/996.

**Closed by oliverschmidt** 2020-04-07 18:21 UTC
Labels: bug, help wanted
