### ISSUE TITLE
cc65 common/interrupt.s is inadequate

### ISSUE THREAD

**Issue by EtchedPixels** [cc65/cc65#499] opened 2017-10-02 17:22 UTC
cc65 self modifies jmpvec which is not in zero page.

In the obscure case where it's mid modifying jmpvec takes an interrupt and then the irq handler causes the same execution path the interrupt corrupts jmpvec and after rti the wrong jump is taken.

the example irq hanlers not only need to do the ZP swap but also save/restore jmpvec+1 and jmpvec+2

**Comment by groessler** [comment] 2017-10-08 22:42
Test program to reproduce?

Or a list of events which could cause a problem?

Your report is quite obscure.

**Comment by EtchedPixels** [comment] 2017-10-11 18:56
Sorry I thought it was blindingly obvious

cc65 generates self modifying code, and doesn't always protect that code against being modified again in an interrupt handler.

Simple case in point is that it generates calls to a helper in runtime that does

                 sta jmpvec+1
                 stx jmpvec+2
jmpvec:
                 jmp $FFFF    ; patched with the address

Now if you get the following

                  sta jmpvec+1
                  stx jmpvec+2
      INTERRUPT ->
                  interrupt code saving ZP as per docs/example
                  does stuff
                  sta jmpvec+1
                  stx jmpvec+2
                   jumps to correct place
                  does other stuff
                  restores ZP variables
                  RTI
  
jmpvec:
                  jmp's off the wrong address (as the IRQ trashed it)

For 65C02 and 65C816 we can replace the store/store/jmp with psh psh rts (1 clock more) but the 6502 version is ugly as sin done that way so it makes more sense I think to save jmpvec+1/2 on irq entry and restore it on irq exit (we can't use ZP because that's another bug - on 65C816 or the HuC there's no guarantee that ZP is 00xx so jmp to 00xx isn't safe.

**Comment by Marrin** [comment] 2017-10-11 22:38
How/Why does the IRQ handler trash `jmpvec`? To cite the docs of the [`set_irq()` function about the handler code](https://cc65.github.io/doc/funcref.html#ss3.184): _„Be careful however not to call C library functions, and do not enable stack checks for the handler function or any other function called from it.“_

So unless the compiler doesn't generate code that writes to `jmpvec`, it should be safe‽

**Comment by EtchedPixels** [comment] 2017-10-12 10:41
The compiler internally generates calls to the jmpvec helper when calling functions by reference.

See codegen.c:g_callind()

So avoiding library routines is not sufficient.

**Comment by oliverschmidt** [comment] 2017-10-13 19:28
> The compiler internally generates calls to the jmpvec helper when calling functions by reference.
See codegen.c:g_callind()
So avoiding library routines is not sufficient.

I see. So we're talking about the code sequence

```
pha
ldy #$%02X
lda (sp),y
sta jmpvec+1
iny
lda (sp),y
sta jmpvec+2
pla
jsr jmpvec
```

> [...] save jmpvec+1/2 on irq entry and restore it on irq exit [...]

I pretty strongly dislike to add additional overhead there for this "special case".

> For 65C02 and 65C816 we can replace the store/store/jmp with psh psh rts (1 clock more) but the 6502 version is ugly [...]

It seems to me that for the 65C02 it isn't that simple too because:
* The code sequence in question does a `pla` between the "store"s and the "jmp".
* The "jmp" is actually a `jsr`.

I must admit I have no good idea on how to fix the issue in an at least remotely clean way...

**Comment by EtchedPixels** [comment] 2017-10-13 20:49
It's not the only case unfortunately because the only reason there are not lots of cases is the fact that the other path for this uses zero page unsafely ( runtime call.s ) amd when you fix that to use jmpvec it shows up in quite a few apps.

For Fuzix I'm just saving jmpvec+1/jmpvec+2 and restoring it for the moment so that interrupts don't break the kernel. For user space I already have to do something much more expensive for signal handling as I need multiple layers of re-entrancy.

I've not found a clean way yet.

**Comment by oliverschmidt** [comment] 2017-10-14 21:55
>> it makes more sense I think to save jmpvec+1/2 on irq entry and restore it on irq exit

> I pretty strongly dislike to add additional overhead there for this "special case".

There was a misunderstanding. What I wanted to express is that I don't want to have additional cycles in the general IRQ handler (at runtime/callirq.s). However here we're talking about C level IRQ functions so the save/restore of the jmpvec could go into common/interrupt.s (which I only now see you already refer to in the title of this issue). There we already save/restore the whole zp segment. I don't see an issue with saving/restoring jmpvec too.

> [...] uses zero page unsafely [...]

Please elaborate why this is unsafe - as common/interrupt.s saves/restores the zp segment.

Apart from all the above I just noticed that runtime/callirq.s already uses jmpvec :-( If I get things right then this means that any IRQ during usage of jmpvec "outside" the IRQ must fail after returning from the IRQ. My first idea is to spend another 3 bytes and have callirq.s use a different "private" patchable jmp in the data segment - as I don't see us nesting IRQs.

**Comment by EtchedPixels** [comment] 2017-10-15 18:04
It does save it - but you hit the problem in my other bug report that ZP may not be 00xx.

**Comment by oliverschmidt** [comment] 2017-10-15 18:14
Please let's try to not mix up the "jmpvec vs. IRQ" issue and the "non-page0-ZP" issue. Otherwise I (and maybe others) are not able to follow you...

So for this issue I see two potential changes:
- Save/restore jmpvec in common/interrupt.s
- Don't use jmpvec in runtime/callirq.s

According to my understanding those two changes would fix all aspects of this issue. Do you agree?

**Comment by greg-king5** [comment] 2017-10-16 04:02
On 2017-10-14 5:55 PM, Oliver Schmidt wrote:
> 
> Apart from all the above, I just noticed that "runtime/callirq.s" already 
> uses jmpvec. :-( If I get things right, then that means that any IRQ 
> during usage of jmpvec "outside" the IRQ must fail after returning from 
> the IRQ. My first idea is to spend another 3 bytes, and have "callirq.s" 
> use a different "private" patchable jmp in the data segment -- as I don't 
> see us nesting IRQs.

It does that.  The entire callirq subroutine is in .data; and, the 
private jmpvec actually is an inline jsrvec.

**Comment by oliverschmidt** [comment] 2017-10-16 07:36
> The entire callirq subroutine is in .data; and, the private jmpvec actually is an inline jsrvec.

You're of course right. I should have spent a few more seconds looking at the code...

So we're left with the common/interrupt.s issue. That makes sense as Uz disliked the idea of C code interrupt handling in the first place so he didn't invest too much thoughts in that area ;-)

**Comment by oliverschmidt** [comment] 2017-10-23 17:02
Fixed with https://github.com/cc65/cc65/commit/c0ce20e9ccb3eb0dfd57d7be8db7b00dafde7471.

**Closed by oliverschmidt** 2017-10-23 17:02 UTC
