### ISSUE TITLE
ca65: expressions don't search for symbols in outer scopes

### ISSUE THREAD

**Issue by tokumaru-x** [cc65/cc65#235] opened 2015-11-26 12:42 UTC
```
.scope
	Symbol = 4
	.scope
		lda #Symbol ;<- this works
		.if Symbol = 4 ;<- this generates an error
			.out "Symbol is 4."
		.endif
	.endscope
.endscope
```

**Comment by fo-fo** [comment] 2015-11-26 13:03
This seems to be a "feature" that everybody runs into eventually. Strictly speaking it's not a bug. Ca65 assumes that `Symbol` might get defined later in the scope so it doesn't see it as a constant (it can't look forward to see whether it will get defined or not). The `lda` works because it doesn't require a constant.

In my opinion, since `.if` generates a compilation-stopping error in this case, it would be better behavior for it to use the value from the outer scope, and set up an assert to make sure that the symbol doesn't get redefined later in the same scope (if it does, that would generate an error because "wrong" value got used for the `.if` condition). However there might be some problems with this approach that I'm unaware of.

**Comment by mrdudz** [comment] 2015-11-26 13:06
On Thursday 26 November 2015, 05:03:51 fo-fo <notifications@github.com> wrote:
> This seems to be a "feature" that everybody runs into eventually. Strictly
> speaking it's not a bug. Ca65 assumes that `Symbol` might get defined later
> in the scope so it doesn't see it as a constant (it can't look forward to
> see whether it will get defined or not). The `lda` works because it doesn't
> require a constant.
> 
> In my opinion, since `.if` generates a compilation-stopping error in this
> case, it would be better behavior for it to use the value from the outer
> scope, and set up an assert to make sure that the symbol doesn't get
> redefined later in the same scope (if it does, that would generate an error
> because "wrong" value got used for the `.if` condition). However there
> might be some problems with this approach that I'm unaware of.

forward references in what essentially resembles a preprocessor expression 
would be totally NOT what i'd expect though.

-- 

http://www.hitmen-console.org    http://magicdisk.untergrund.net
http://www.pokefinder.org        http://ar.pokefinder.org

I have always wished that my computer would be as easy to use as my telephone. 
My wish has come true. I no longer know how to use my telephone. 
<Bjarne Stroustrup>

**Comment by fo-fo** [comment] 2015-11-26 13:24
> forward references in what essentially resembles a preprocessor expression
> would be totally NOT what i'd expect though.

I'm not sure what point you're trying to make. I think it's important to keep the scope search rules same regardless of context (which, I assume, is the justification for the current behavior), so that's why I suggested setting up the assert so that the behavior stays consistent. But even with that approach there are probably some degenerate cases that break the consistency. (What if the `.if` block itself redefines `Symbol` to some other value in the same scope? You could arguably say that the scope search rules were not respected.)

**Comment by greg-king5** [comment] 2015-11-26 19:56
>     .scope
>         Symbol = 4
>         .scope
>             lda #Symbol ;<- this works
>             .if Symbol = 4 ;<- this generates an error
>                 .out "Symbol is 4."
>             .endif
>         .endscope
>     .endscope

It is a known bug, that Uz never got around to fixing.  The ca65 code that handles constant expressions does not climb the "ladder" of scopes while looking for a symbol.  The code that handles non-constant expressions does climb the ladder.  The work-around for that bug is:
name the scope; then, use the namespace operator:

    .scope scope_name
        Symbol = 4
        .scope
            lda #Symbol ;<- this works
            .if scope_name::Symbol = 4 ;<- this now works
                .out "Symbol is 4."
            .endif
        .endscope
    .endscope

**Comment by fo-fo** [comment] 2015-11-26 20:08
> It is a known bug, that Uz never got around to fixing

Here's Uz pretty explicitly saying that it's a feature, not a bug: http://www.cc65.org/mailarchive/2011-07/9539.html

Also consider that if this bug is fixed naively, you get inconsistent behavior:

```
.scope
    Symbol = 4
    .scope
        lda #Symbol ; With current behavior this will generate lda #5
        .if Symbol = 4 ; If "bug" is "fixed", this evaluates to true
            .out "Symbol is 4."
        .endif
        Symbol = 5
    .endscope
.endscope
```

**Comment by fo-fo** [comment] 2015-11-27 06:32
> and set up an assert to make sure that the symbol doesn't get redefined later in the same scope

It occurred to me, that in fact the assert wouldn't have to check this, it could simply check that Symbol=4 (if Symbol in same scope gets declared to the same value later, nothing was miscompiled). The evaluation of the assert would need to be delayed (can't treat Symbol as a constant in it).

**Comment by oliverschmidt** [comment] 2016-08-05 11:37
Although there are different opinions regarding the classification of this issue I don't see that there is something to do about it. So it seems appropriate to me to close it.

**Closed by oliverschmidt** 2016-08-05 11:37 UTC

**Comment by silverdr** [comment] 2016-08-05 11:48
Except putting the above examples in the KnownIssues/FAQ, unless it's already there ;-)

**Comment by oliverschmidt** [comment] 2016-08-05 12:07
I'm pretty sure they aren't. I don't really understand this issue. Could you imagine to take care of this?

**Comment by silverdr** [comment] 2016-08-05 13:29
I _think_ I understand it, yet I don't feel confident enough of my understanding to write a fully reliable explanation what/why/how. If nobody else volunteers I may try but it would need a good review of those who know better anyway.

**Comment by greg-king5** [comment] 2016-08-06 07:01
I completely had forgotten about that issue!  It explains our scoping/namespace problem in the planned `.setdp` feature (mentioned in PR #319).

I disagree with Uz's rationale about `.if`; I agree with Agent Friday (on the old mailing list) and mrdudz (in this thread).  `.if` should have no forward referencing; it should be able to recognize (already-defined) outer-scope constants.

But, `.setdp` is different.  It affects machine-code generation, which does forward references.  We cannot make a perfect fix.  But, I hope that we can create something that is "acceptable".

**Comment by fo-fo** [comment] 2016-08-06 07:21
Do you really think it's a good idea that a symbol value differs depending on the context it's used in? Again:

```
foo = 111
.scope
  .out .sprintf( "loading %d", foo ) ; would print 111
  lda #foo ; would load 222
  foo = 222
.endscope
```

I didn't receive any comments on my proposal, but I think it's the best of both worlds: you would be able to reference constant symbols from outer scopes (by far the most common use case), as well as getting an error (or a warning) about inconsistency if the symbol of the same name is later redefined in the same scope. This change would be completely backwards compatible.

**Comment by greg-king5** [comment] 2016-08-07 22:41
> Do you really think it's a good idea that a symbol value differs depending on the context it's used in?

Yes, of course!  That is the purpose of scopes, isn't it?  They let us change the context, and change a symbol's value, without getting an error message.

We can take the concept further; and, add "timing" to the context.
```asm
foo = 111
.scope
  lda #foo ; will load 222 later
  .out .sprintf( "foo CURRENTLY is %d.", foo ) ; should print 111
  foo = 222
  .out .sprintf( "foo CURRENTLY is %d.", foo ) ; prints 222
.endscope
```
Those `.out` lines use `foo` at an early stage of the assembly (before the entire file has been scanned;  one of them before, and one of them after, `foo` is changed), while `lda #foo` uses it at a later stage (after the source file has been scanned; after `foo` has been redefined locally).

**Comment by mrdudz** [comment] 2016-08-07 22:50
thats just terrible. in the same scope, the value of the symbol should always be the same really - a programmer shouldnt need to know about how the assembler works internally.

**Comment by greg-king5** [comment] 2016-08-07 22:56
In my opinion, your proposal seems useful -- but, it would be for something like the `.setdp` feature, not for things like `.if` directives.

**Comment by greg-king5** [comment] 2016-08-08 01:07
What I wrote there is just another way of describing things that programmers always have needed to know about writing source files for ca65.  There are two big groups of things: assembler directives/commands and Assembly Code (which makes Machine Code).

Most things in the first group require constant expressions.
1. You can't use imported names.
2. You can't use relocatable names.
3. You must define a name before you use it.

The second group doesn't have those restrictions.

Being able to work comfortably with the third restriction is the reason why the two groups should be able to see different values for the same name -- even when objects from the two groups are sitting near each other in a source file.

---
By the way, `.scope`/`.proc` isn't the only thing that lets us change a name's value.  The `.repeat` and `.set` directives do it, too!

**Comment by fo-fo** [comment] 2016-08-08 09:14
> Do you really think it's a good idea that a symbol value differs depending on the context it's used in?

I should not have used the term "symbol's value" here, what I meant was that the scope resolution rules would be different depending on context (and by "context" I mean things like "in an .if statement", "as an instruction operand").

> In my opinion, your proposal seems useful -- but, it would be for something like the .setdp feature, not for things like .if directives.

I don't really see any reason why it shouldn't apply to all constant expressions. Again, for consistency, it would be good it behaves the same everywhere. My proposal is nothing more but "give an error when inconsistent usage is detected".

> By the way, .scope/.proc isn't the only thing that lets us change a name's value. The .repeat and .set directives do it, too!

Those don't lead to inconsistent behavior, though, like the one in your example.

**Comment by jbrandwood** [comment] 2016-08-09 18:09
> mrdudz commented 2 days ago
>
> thats just terrible. in the same scope, the value of the symbol should always be the same really - a
> programmer shouldnt need to know about how the assembler works internally.
>
> greg-king5 commented 2 days ago
>
> 3. You must define a name before you use it.

Since this was linked from pull request #319 and the disucssions of the new ".setdp" directive, I thought that I'd put in my 2c.

I've got to agree with mrdudz here ... IMHO you should *never* have two different values for the same symbol name within a scope.

If you want to use the same name for something in both outer and inner scopes, then you *must* redefine it within the inner scope *before* you use it within that scope.

If a name is used within the inner scope (referring to the outer scope's symbol), and the name is then later redefined within the same inner scope, then that's an error and should be flagged.

The only exception to that would be for local symbols that *never* refer to things outside the current scope and are normally just used for local branches.

From what I can see, CA65's current symbol-handling code is flawed and breaks that simple-and-understandable logic, and the way that it's done now, and the inconsistencies within the current processing, is causing problems.

Perhaps I'm missing something.

Just because it's *possible* to program symbol-table handling code that allows for the local-use-before-local-definition scenario that's presented in the examples here, it's never IMHO a good idea in *practice*, and in 30+ years of programming, I've never seen anything like these contrived usage examples that wasn't anything other than a bug or the cause of a future-bug later on in the code.

As far as I can see the symbol-table logic should be as easy as having any name within a scope having 2 bits ... 1 for "referenced" and 1 for "defined".

Any new name that is defined within a scope should be added to the scope's symbol-table and marked as "defined".

Any new name that is referenced within a scope should be added to the symbol-table and marked as "referenced", and if that name resolves to the same name in a higher scope, then it should also be marked as "defined", and a link added to the symbol in the higher scope (even if the name has not yet been "defined" within the higher scope).

Then you just raise an error if the name is "defined" twice within the same scope.
