### ISSUE TITLE
Building the HTML documentation fails

### ISSUE THREAD

**Issue by spektro** [cc65/cc65#416] opened 2017-04-04 00:29 UTC
I tried building the cc65 HTML documentation but got a lot of warnings like this:

> Unescaped left brace in regex is deprecated, passed through in regex;

and finally this error:

> Makefile:43: recipe for target '../info/geos.info' failed
> make: *** [../info/geos.info] Error 2

How to reproduce:
1) Change the current working directory to 'cc65/doc'.
2) Enter command 'make'.

Tested with Linux Mint 18.1 'Serena'

**Comment by oliverschmidt** [comment] 2017-04-04 10:07
I presume that something with your local setup is strange. As you can see in https://github.com/cc65/cc65/blob/master/.travis.yml#L12 building the documentation is part of Travis CI tests. And there we haven't seen any issues with building geos.info.

The Travis CI tests run on Ubuntu 12.04 or 14.04 LTS Server Edition 64 bit and do https://github.com/cc65/cc65/blob/master/.travis.yml#L5

**Comment by spektro** [comment] 2017-04-04 22:45
I think you're right. I'm a novice Linux user but it seems that a bug in Perl (version 5.22.1) is causing the warnings and the error.

Despite of the errors, the Doc Makefile created an html directory and stored 46 html files in it. The directory contains also doc.css and doc.png files. All those files seems to be OK.

**Comment by oliverschmidt** [comment] 2017-04-05 07:12
Thanks for the feedback. I'll close this now.

**Closed by oliverschmidt** 2017-04-05 07:12 UTC

**Comment by greg-king5** [comment] 2017-04-05 08:22
It's a "legacy bug" in Linuxdoc-tools' Perl scripts.  Awhile back, the syntax of Perl regular expresions was changed.  Braces are a special directive; now, we must show that, by prefixing the left-brace with a backslash.  Linuxdoc-tools' scripts were written before that became needed.  The warnings are annoying but harmless.  The HTML files are built.  "`make -C doc html`" works.

Your problem with "geos.info" must be caused by something else.  Do you have any files in the "`info/`" subdirectory?

**Comment by spektro** [comment] 2017-04-06 11:46
No, the 'info' subdirectory is empty.

I tried entering 'make -C doc html' command in the cc65 directory and it worked - no error. The error appears when I enter 'make' in the 'cc65/doc/' directory.

**Comment by spiro-trikaliotis** [comment] 2017-04-06 20:42
Hello,

* On Thu, Apr 06, 2017 at 04:46:17AM -0700 Janne Peräaho wrote:
> No, the 'info' subdirectory is empty.
> 
> I tried entering 'make -C doc html' command in the cc65 directory and it worked
> - no error. The error appears when I enter 'make' in the 'cc65/doc/' directory.

That's interesting. I also noted in my Makefile for another project that
make -C xxx TARGET and cd xxx; make TARGET do not perform the same, and
I have problems like your one once in a while.

I still have not figured out what is actually happening. If anyone finds
out what the problem is, I would be very thankful to know, too.

Regards,
Spiro.

-- 
Spiro R. Trikaliotis
http://www.trikaliotis.net/

**Comment by greg-king5** [comment] 2017-04-07 08:11
> I also noted in my Makefile for another project that `make -C xxx TARGET` and `cd xxx; make TARGET` do not perform the same; and, I have problems like your one, once in a while.

That's very strange!

But, spektro's TARGETs are different.  He is trying to do "`make`", which becomes "`make doc`", which becomes "`make html info`".  The `html` goal works; the `info` goal fails.  Oliver pointed to the most likely reason when he mentioned [this line](https://github.com/cc65/cc65/blob/master/.travis.yml#L5) in `".travis.yml"`.  Linux Mint might be like Ubuntu; on Mint, Linuxdoc-tools might need a second package, in order to create the "info" version of documentation.

@spektro, look for a Mint package that has a name that's similar to `"linuxdoc-tools-info"`.  Install it; then, try
```sh
cd doc
make info
```

However, ...
the "info" files aren't needed -- they are only an alternate view of the documentation.  They're useful if you work in a text console most of the time.  But, if you work in your system's graphics mode most of the time, then the HTML files are easier to use; and, they look better.

**Comment by spektro** [comment] 2017-04-19 20:43
Installing the 'linuxdoc-tools-info' fixed the 'info' files problem.
