### ISSUE TITLE
Atari: Setting pixel data 10x slower than before

### ISSUE THREAD

**Issue by 8bit-Dude** [cc65/cc65#1298] opened 2020-10-24 02:44 UTC
This is a strange bug, probably one for Chris Groessler!  :-)

I have been using a 2018 version of CC65 for a while, and decided to upgrade to latest for next release of 8bit-Unity. Most functions work normally (such as loading bitmaps), but one function for setting pixels has become incredibly slow.
The code is as follows (compiled using default atarixl.cfg):
```c
#define BITMAPRAM1 (0x7010) // 7010-8f50 (bitmap frame 1)
#define BITMAPRAM2 (0xa010) // a010-bf50 (bitmap frame 2)

void SetPixel(unsigned int pixelX, unsigned int pixelY, unsigned char color)
{
	unsigned int offset;
	unsigned char shift, mask, col1, col2;	

	// Compute pixel location
	offset = 40*pixelY + pixelX/4;
	shift = 6 - 2*(pixelX%4);
	mask = 255 - (3 << shift);
	if ((pixelY+pixelX)%2) {
		col2 = (color%4) << shift;
		col1 = (color/4) << shift;
	} else {
		col1 = (color%4) << shift;
		col2 = (color/4) << shift;
	}

	// Set color/color2 in dual buffer
	POKE((char*)BITMAPRAM1+offset, (PEEK((char*)BITMAPRAM1+offset) & mask) | col1);
	POKE((char*)BITMAPRAM2+offset, (PEEK((char*)BITMAPRAM2+offset) & mask) | col2);
}
```
I wonder if the system is waiting for a VSYNC or something, whenever I touch the bitmap ram?

**Comment by oliverschmidt** [comment] 2020-10-24 07:32
I guess that the issue rather relates to different code generated by the compiler...

**Comment by polluks** [comment] 2020-10-24 08:07
Indeed, no job for Groessler. Firstly you may turn off the optimiser.

**Comment by 8bit-Dude** [comment] 2020-10-24 12:04
I am trying to produce a sample code that replicates the issue without needing 8bit-unity.

**Comment by jmr** [comment] 2020-10-24 14:18
Some of it is probably from the changes in integral conversion semantics, but 10x seems extreme. It should be easy to put the above code in a loop and test with `sim65 -c`, if this function is indeed the problem.

**Comment by 8bit-Dude** [comment] 2020-10-24 14:34
Alright, I have an interesting benchy right here:

`
#include <stdlib.h>
#include <conio.h>
#include <peekpoke.h>
#include <time.h>


#define BITMAPRAM1 (0x7010) // 7010-8f50 (bitmap frame 1)
#define BITMAPRAM2 (0xa010) // a010-bf50 (bitmap frame 2)

int main (void)
{
	unsigned int i, offset;
	unsigned char shift, mask, col1, col2, pixelX, pixelY, color = 3;	
	clock_t timer = clock();

    /* Clear the screen again */
    clrscr ();
	
	for (i=0; i<1024; i++) {
		// Compute pixel location
		offset = 40*pixelY + pixelX/4;
		shift = 6 - 2*(pixelX%4);
		mask = 255 - (3 << shift);
		if ((pixelY+pixelX)%2) {
			col2 = (color%4) << shift;
			col1 = (color/4) << shift;
		} else {
			col1 = (color%4) << shift;
			col2 = (color/4) << shift;
		}

		// Set color/color2 in dual buffer
		POKE((char*)BITMAPRAM1+offset, (PEEK((char*)BITMAPRAM1+offset) & mask) | col1);
		POKE((char*)BITMAPRAM2+offset, (PEEK((char*)BITMAPRAM2+offset) & mask) | col2);
		
		pixelX++; pixelY++;
	}
	
	cprintf("%lu", clock()-timer);
	while (1);
	
    /* Done */
    return EXIT_SUCCESS;	
}`

Running this on my 2018 version of CC65 prints "55".
On the latest CC65, it prints "201" with optimization, and "244" without optimization.

Not quite 10x, only 4x slower.  :-)

**Comment by jmr** [comment] 2020-10-24 17:54
What does `cc65 --version` say on your 2018 version?

I'm seeing a 2x difference between c4698df and `c4698df~` with `sim65 -c` and a slightly different benchmark. Yours is testing up to `pixelX == pixelY == 1023`, which seems like it might be stomping random memory.

**Comment by 8bit-Dude** [comment] 2020-10-24 21:20
Trying with pixelX = pixelY =0 gives pretty much the same result (P.S: both are unsigned char anyway).
The "2018" version is cc65 V2.17 - Git 180bb08

**Comment by jmr** [comment] 2020-10-25 07:33
Here's the diff between `4698df~` and c4698df:

```
--- set-pixel.s.old     2020-10-25 08:22:08.000000000 +0100
+++ set-pixel.s.new     2020-10-25 08:22:09.000000000 +0100
@@ -8,149 +8,147 @@

 .segment       "CODE"

 ;
 ; {
 ;
        jsr     pusha
 ;
 ; offset = 40*pixelY + pixelX/4;
 ;
        jsr     decsp6
        ldy     #$0A
        jsr     pushwysp
        lda     #$28
        jsr     tosumula0
-       sta     ptr1
-       stx     ptr1+1
-       ldy     #$0A
+       jsr     pushax
+       ldy     #$0C
        jsr     ldaxysp
        jsr     shrax2
-       clc
-       adc     ptr1
-       pha
-       txa
-       adc     ptr1+1
-       tax
-       pla
+       jsr     tosaddax
        ldy     #$04
        jsr     staxysp
 ;
 ; shift = 6 - 2*(pixelX%4);
 ;
        lda     #$06
        jsr     pusha0
        ldy     #$0B
        lda     (sp),y
        and     #$03
        asl     a
        bcc     L004C
        ldx     #$01
 L004C: jsr     tossubax
        ldy     #$03
        sta     (sp),y
 ;
 ; mask = 255 - (3 << shift);
 ;
        lda     #$FF
        jsr     pusha0
-       ldy     #$05
-       lda     (sp),y
-       tay
        lda     #$03
-       jsr     aslaxy
+       jsr     pusha0
+       ldy     #$07
+       lda     (sp),y
+       jsr     tosaslax
        jsr     tossubax
        ldy     #$02
        sta     (sp),y
 ;
 ; if ((pixelY+pixelX)%2) {
 ;
        ldy     #$0A
+       jsr     pushwysp
+       ldy     #$0C
        jsr     ldaxysp
-       clc
-       ldy     #$07
-       adc     (sp),y
-       pha
-       txa
-       iny
-       adc     (sp),y
-       pla
+       jsr     tosaddax
        and     #$01
        beq     L000A
 ;
 ; col2 = (color%4) << shift;
 ;
        ldy     #$06
        lda     (sp),y
-       ldx     #$00
-       and     #$03
+       jsr     pusha0
+       lda     #$04
+       jsr     tosmoda0
        sta     ptr1
+       stx     ptr1+1
        ldy     #$03
        lda     (sp),y
        tay
        lda     ptr1
-       jsr     shlaxy
+       ldx     ptr1+1
+       jsr     aslaxy
        ldy     #$00
        sta     (sp),y
 ;
 ; col1 = (color/4) << shift;
 ;
        ldy     #$06
        lda     (sp),y
-       lsr     a
-       lsr     a
+       jsr     pusha0
+       lda     #$04
+       jsr     tosdiva0
        sta     ptr1
+       stx     ptr1+1
        ldy     #$03
        lda     (sp),y
        tay
        lda     ptr1
-       ldx     #$00
-       jsr     shlaxy
+       ldx     ptr1+1
+       jsr     aslaxy
        ldy     #$01
 ;
 ; } else {
 ;
        jmp     L004D
 ;
 ; col1 = (color%4) << shift;
 ;
 L000A: ldy     #$06
        lda     (sp),y
-       ldx     #$00
-       and     #$03
+       jsr     pusha0
+       lda     #$04
+       jsr     tosmoda0
        sta     ptr1
+       stx     ptr1+1
        ldy     #$03
        lda     (sp),y
        tay
        lda     ptr1
-       jsr     shlaxy
+       ldx     ptr1+1
+       jsr     aslaxy
        ldy     #$01
        sta     (sp),y
 ;
 ; col2 = (color/4) << shift;
        ldy     #$06
        lda     (sp),y
-       lsr     a
-       lsr     a
+       jsr     pusha0
+       lda     #$04
+       jsr     tosdiva0
        sta     ptr1
+       stx     ptr1+1
        ldy     #$03
        lda     (sp),y
        tay
        lda     ptr1
-       ldx     #$00
-       jsr     shlaxy
+       ldx     ptr1+1
+       jsr     aslaxy
        ldy     #$00
 L004D: sta     (sp),y
 ;
 ; POKE((char*)BITMAPRAM1+offset, (PEEK((char*)BITMAPRAM1+offset) & mask) | col1);
 ;
        ldy     #$05
        jsr     ldaxysp
        clc
        adc     #<($7010)
        sta     sreg
        txa
        adc     #>($7010)
        sta     sreg+1
        ldy     #$05
        jsr     ldaxysp
```

So it looks like optimizations are being lost because of the `unsigned -> signed` change.  Let me see what we can get back by rewriting `SetPixel`.

**Comment by 8bit-Dude** [comment] 2020-10-25 09:18
Why does a conversion unsigned -> signed occur? (all vars are declared as unsigned)

**Comment by jmr** [comment] 2020-10-25 11:01
The commit message of c4698df explains. That's the way the standard defines it. `char`  and `unsigned char` expressions are converted to `int`. `int` is supposed to be the fastest type, but it is also supposed to be >= 16 bits, so there's a bit of a problem on these 8-bit processors that C was never intended to support. Probably they picked `int` instead of `unsigned` since it's more intuitive, and integral constants are `int`.

Anyway, it looks like mostly `/` & `%` were causing the problems. Here's a version (correctness completely untested) that's faster with `HEAD` than your old version was in 2018:

```
void SetPixel(unsigned int pixelX, unsigned int pixelY, unsigned char color)
{
    unsigned int offset;
    unsigned char shift, mask, col1, col2;

    // Compute pixel location
    offset = pixelY * 8;
    offset += offset * 4;
    offset += pixelX / 4;

    shift = 6 - 2*(pixelX%4);
    mask = ~(3 << shift);

    if ((pixelY+pixelX)%2) {
        col2 = (color & 3) << shift;
        col1 = (color >> 2) << shift;
    } else {
        col1 = (color & 3) << shift;
        col2 = (color >> 2) << shift;
    }

    POKE((char*)BITMAPRAM1+offset, (PEEK((char*)BITMAPRAM1+offset) & mask) | col1);
    POKE((char*)BITMAPRAM2+offset, (PEEK((char*)BITMAPRAM2+offset) & mask) | col2);
}
```

You could probably take this further, and expand the `shift`/`mask` computation to a switch, etc.

The generated code still looks pretty horrific. I want to try to keep things as `unsigned` or `char` when possible (still keeping C semantics), but haven't had the time recently.

**Comment by acqn** [comment] 2020-10-25 11:53
You may add a `U` suffix to the numeric constants if you are only doing unsigned arithmetics.

**Comment by jmr** [comment] 2020-10-25 12:13
Good point, that is much easier. Expanding the offset computation still helps, though.  (A bit annoying, since this is the sort of thing compilers are supposed to do.) 

It would still be nice to make the generated code use `unsigned char` as much as possible.

**Comment by 8bit-Dude** [comment] 2020-10-25 12:42
Thanks for taking time to look into this issue and think it through.

I have combined both your advice, and tested the following code:

`	for (i=0; i<1024; i++) {
		// Compute pixel location
		offset = 40*pixelY + pixelX/4;
		shift = 6 - 2*(pixelX%4);
		mask = 255 - (3 << shift);
		if ((pixelY+pixelX)%2) {
			col2 = (color%4) << shift;
			col1 = (color/4) << shift;
		} else {
			col1 = (color%4) << shift;
			col2 = (color/4) << shift;
		}

		// Set color/color2 in dual buffer
		POKE((char*)BITMAPRAM1+offset, (PEEK((char*)BITMAPRAM1+offset) & mask) | col1);
		POKE((char*)BITMAPRAM2+offset, (PEEK((char*)BITMAPRAM2+offset) & mask) | col2);
	}`

With cc65 V2.17 - Git 180bb08, the number of tick falls down from 59 -> 55.
With cc65 head, the number of tick falls down from 246 -> 190.
It's better, but still not quite enough in terms of performance.

Of course, I could just slot in the ASM code produced by old cc65, but I worry about the fact that I use a lot of uint16 calculations throughout the code. Do let me know if you think that further optimization of the code is possible.

**Comment by jmr** [comment] 2020-10-25 12:56
It's strange that you're seeing so little improvement. How accurate are the sim65 cycle counts supposed to be? Can you also run your benchmark on sim65? `cl65 -O -t sim6502 set-pixel.c && sim65 -c set-pixel`. Just remove the timer stuff.

Expanding the multiplication by 40 helps, as would replacing the mask/shift computation by a switch statement, as I said before. How fast does it need to get?

**Comment by oliverschmidt** [comment] 2020-10-25 13:10
> How accurate are the sim65 cycle counts supposed to be?

Perfectly accurate: https://github.com/cc65/cc65/blob/master/src/sim65/6502.c#L3283

**Comment by acqn** [comment] 2020-10-25 13:10
I guess you may apply more `u`s....

**Comment by 8bit-Dude** [comment] 2020-10-25 13:30
Some further results:
  For sim65:   I get 2764203 cycles in old cc65, and 4273579 cycles in new cc65.
  For c64:   I get 181 ticks in old c65,  359 ticks in new cc65.

How good does it need to be? This is a pixel setting function, so...

**Comment by jmr** [comment] 2020-10-25 13:41
Is this with `-O`? and the code from https://github.com/cc65/cc65/issues/1298#issuecomment-716142071 ?

**Comment by 8bit-Dude** [comment] 2020-10-25 13:42
Yes sir!

**Comment by acqn** [comment] 2020-10-25 14:10
```asm
;
; offset += pixelX/4;
;
	ldy     #$06
	lda     (sp),y
	jsr     pusha0
	lda     #$04
	jsr     tosdiva0
	ldy     #$0B
	jsr     addeqysp
```
vs
```asm
;
; offset += pixelX/4u;
;
	ldy     #$06
	ldx     #$00
	lda     (sp),y
	lsr     a
	lsr     a
	ldy     #$0B
	jsr     addeqysp
```

**Comment by jmr** [comment] 2020-10-25 19:18
I have your code from https://github.com/cc65/cc65/issues/1298#issuecomment-716142071 with`void main(void) { SetPixel(0, 0, 0); }` and am getting 1432051 from sim65 at HEAD (2fcd8b9). That's off by a factor of 3. How are you calling `SetPixel`?

**Comment by 8bit-Dude** [comment] 2020-10-29 08:08
Sorry for late reply. I did some further test with very latest SVN head against cc65 V2.17 - Git 180bb08.
The results are (v2.17) -> (head):
    C64:     181 Ticks ->  276 Ticks
    A8 XL:  129 Ticks -> 190 Ticks
    Sim65:  2759083 cycles -> 4237735 cycles

The code I ran was:
   
#define BITMAPRAM1 (0x7010) // 7010-8f50 (bitmap frame 1)
#define BITMAPRAM2 (0xa010) // a010-bf50 (bitmap frame 2)

int main (void)
{
    unsigned int i, offset;
    unsigned char shift, mask, col1, col2, pixelX, pixelY, color = 3;	
#ifndef __SIM6502__
    clock_t timer = clock();
#endif;
	for (i=0; i<1024; i++) {
		// Compute pixel location
		offset = 40u*pixelY;
		offset += pixelX/4u;
		
		shift = 6 - 2*(pixelX%4);
		mask = ~(3 << shift);
		
		if ((pixelY+pixelX)%2) {
			col2 = (color&3) << shift;
			col1 = (color/4u) << shift;
		} else {
			col1 = (color&3) << shift;
			col2 = (color/4u) << shift;
		}

		// Set color/color2 in dual buffer
		POKE((char*)BITMAPRAM1+offset, (PEEK((char*)BITMAPRAM1+offset) & mask) | col1);
		POKE((char*)BITMAPRAM2+offset, (PEEK((char*)BITMAPRAM2+offset) & mask) | col2);
	}
#ifndef __SIM6502__	
	cprintf("%lu", clock()-timer);
	while (1);
#endif;
    return EXIT_SUCCESS;	
}

**Comment by jmr** [comment] 2020-10-29 08:45
You're not initializing `pixelX` or `pixelY`, but that doesn't seem to make a big difference.

`cl65 V2.18 - Git 2fcd8b9` (HEAD)
`2584968 cycles` with `-O`. Even without `-O` is less than what you have.

How can we be getting answers off by 50%?

**Comment by IrgendwerA8** [comment] 2020-11-05 00:33
> offset = 40u*pixelY;

You could check usage of "mul40" from
https://github.com/cc65/cc65/blob/master/include/cc65.h

**Comment by jmr** [comment] 2020-11-05 08:22
I have the original version (no unsigned constants or manual strength reduction) down to 1929608 cycles on my local branch.

I'll wait for #1315 and #1321 to be merged before sending the next PR.

**Comment by jmr** [comment] 2020-11-05 08:31
> You could check usage of "mul40" from
> https://github.com/cc65/cc65/blob/master/include/cc65.h

Interesting. That saves about 200 cycles / call vs `* 40u`. Why aren't these just automatically used via codegen (with appropriate code size options, if that's an issue)?

**Comment by oliverschmidt** [comment] 2020-11-05 20:26
> Why aren't these just automatically used via codegen (with appropriate code size options, if that's an issue)?

* They are way to special.
* Only after March, 2019 they became available for all targets (https://github.com/cc65/cc65/commit/db8bd84a82992d7d29fdd46443c194c1d8ea37fd).

**Comment by jmr** [comment] 2020-11-10 19:48
Here's the main difference with #1328:

```
 ;
 ; if ((pixelY+pixelX)%2) {
 ;
-       ldy     #$02
+       ldy     #$01
        lda     (sp),y
-       clc
-       dey
-       adc     (sp),y
-       and     #$01
-       beq     L0015
+       jsr     pusha0
+       ldy     #$04
+       lda     (sp),y
+       jsr     tosadda0
+       jsr     pushax
+       ldx     #$00
+       lda     #$02
+       jsr     tosmoda0
+       stx     tmp1
+       ora     tmp1
+       beq     L0006
```

I don't think this can be easily fixed since `pixelY + pixelX` has type `int` even though both operands are `unsigned char`. I could imagine some analysis that `0 <= pixelY + pixelX <= 2 * 255`. Therefore, we could do an unsigned mod rather than a signed one. I'm not sure how hard that is, but it could be worth thinking about. 

Changing `(pixelY+pixelX)%2` to `(pixelY+pixelX)%2U` restores the old performance (along with #1328). The rest of the code can remain the same.

**Comment by jmr** [comment] 2020-11-11 10:47
Maybe there'a another way. Since this is a remainder in a test, we don't care if it's `1` or `-1`, just when it's zero/non-zero, which is the same for signed and unsigned remainder.

**Comment by greg-king5** [comment] 2020-11-15 23:58
> Maybe there'a another way. Since this is a remainder in a test, we don't care if it's `1` or `-1`, just when it's zero/non-zero, which is the same for signed and unsigned remainder.

You're right!  It's the same as
```c
if ((pixelY ^ pixelX) & 0b1) {
```

**Comment by IrgendwerA8** [comment] 2020-11-16 09:13
Maybe it's just me. But in general I would choose a table driven approach for the shifts and the 4 colours...

**Comment by IrgendwerA8** [comment] 2020-11-17 23:37
> A8 XL: 129 Ticks -> 190 Ticks

With 060417b0dc1018adc79fd16d0eb97c61d729aea3  'mul40' and two small tables I'm down to 45 on the Atari.

```
#include <stdlib.h>
#include <conio.h>
#include <peekpoke.h>
#include <time.h>
#include <cc65.h>

#define BITMAPRAM1 (0x7010) // 7010-8f50 (bitmap frame 1)
#define BITMAPRAM2 (0xa010) // a010-bf50 (bitmap frame 2)

unsigned char x2Shifts[] = { 6, 4, 2, 0 };
unsigned char x2Mask[] = { 0b00111111,
                           0b11001111,
                           0b11110011,
                           0b11111100 };

int main (void)
{
    unsigned int i, offset;
    unsigned char shift, mask, col1, col2, pixelX, pixelY, xNibble, color = 3; 
#ifndef __SIM6502__
    clock_t timer = clock();
#endif;
  for (i=0; i<1024; i++) {
    // Compute pixel location
    offset = mul40(pixelY);
    offset += pixelX/4u;
    
    xNibble = pixelX & 3;
    shift = x2Shifts[xNibble];
    mask = x2Mask[xNibble];
    
    if ((pixelY+pixelX)%2) {
      col2 = (color&3) << shift;
      col1 = (color/4u) << shift;
    } else {
      col1 = (color&3) << shift;
      col2 = (color/4u) << shift;
    }

    // Set color/color2 in dual buffer
    POKE((char*)BITMAPRAM1+offset, (PEEK((char*)BITMAPRAM1+offset) & mask) | col1);
    POKE((char*)BITMAPRAM2+offset, (PEEK((char*)BITMAPRAM2+offset) & mask) | col2);
  }
#ifndef __SIM6502__ 
  cprintf("%lu", clock()-timer);
  while (1);
#endif;
    return EXIT_SUCCESS;  
}
```

**Comment by greg-king5** [comment] 2020-11-18 15:00
> ```c
> if ((pixelY+pixelX)%2) {
> ```

Use
```c
if ((pixelY^pixelX)&1) {
```
It does the same thing, but no `clc`.  It's only one byte smaller and two cycles faster, but every little bit helps!

**Comment by polluks** [comment] 2020-11-18 17:30
@greg-king5 Maybe the compiler could automatically convert add to xor like this?

**Comment by jmr** [comment] 2020-11-18 17:35
`+` vs `^` is small, but `% 2` vs `& 1` should be a huge difference. I think it needs to be `% 2U` to be strength reduced to and.

**Comment by jmr** [comment] 2020-11-18 18:52
> @greg-king5 Maybe the compiler could automatically convert add to xor like this?

I'm working on tracking the target type of expressions, mostly to set `CF_FORCECHAR` when possible. Tracking the maximum value / relevant bits from `%` or `&` should be a small extension.

**Comment by 8bit-Dude** [comment] 2020-11-24 01:14
> > A8 XL: 129 Ticks -> 190 Ticks
> 
> With [060417b](https://github.com/cc65/cc65/commit/060417b0dc1018adc79fd16d0eb97c61d729aea3) 'mul40' and two small tables I'm down to 45 on the Atari.
> 
> ```c
> #include <stdlib.h>
> #include <conio.h>
> #include <peekpoke.h>
> #include <time.h>
> #include <cc65.h>
> 
> #define BITMAPRAM1 (0x7010) // 7010-8f50 (bitmap frame 1)
> #define BITMAPRAM2 (0xa010) // a010-bf50 (bitmap frame 2)
> 
> unsigned char x2Shifts[] = { 6, 4, 2, 0 };
> unsigned char x2Mask[] = { 0b00111111,
>                            0b11001111,
>                            0b11110011,
>                            0b11111100 };
> 
> int main (void)
> {
>     unsigned int i, offset;
>     unsigned char shift, mask, col1, col2, pixelX, pixelY, xNibble, color = 3; 
> #ifndef __SIM6502__
>     clock_t timer = clock();
> #endif;
>   for (i=0; i<1024; i++) {
>     // Compute pixel location
>     offset = mul40(pixelY);
>     offset += pixelX/4u;
>     
>     xNibble = pixelX & 3;
>     shift = x2Shifts[xNibble];
>     mask = x2Mask[xNibble];
>     
>     if ((pixelY+pixelX)%2) {
>       col2 = (color&3) << shift;
>       col1 = (color/4u) << shift;
>     } else {
>       col1 = (color&3) << shift;
>       col2 = (color/4u) << shift;
>     }
> 
>     // Set color/color2 in dual buffer
>     POKE((char*)BITMAPRAM1+offset, (PEEK((char*)BITMAPRAM1+offset) & mask) | col1);
>     POKE((char*)BITMAPRAM2+offset, (PEEK((char*)BITMAPRAM2+offset) & mask) | col2);
>   }
> #ifndef __SIM6502__ 
>   cprintf("%lu", clock()-timer);
>   while (1);
> #endif;
>     return EXIT_SUCCESS;  
> }
> ```

Those modifications look very intersting, particularly the use of tables for mask and shift.
I will give it a try and report back. I will also apply similar changes to other parts of my code. :-)

**Comment by mrdudz** [comment] 2022-08-26 21:51
can we close this? it seems like this is not a bug in the compiler.

**Comment by IrgendwerA8** [comment] 2022-08-27 08:20
Shouldn't we wait until he tries and report back? :grin:

**Comment by mrdudz** [comment] 2022-11-18 19:21
closing because of no feedback (and not a compiler bug :))

**Closed by mrdudz** 2022-11-18 19:21 UTC
Labels: bug, cc65
