### ISSUE TITLE
make -j

### ISSUE THREAD

**Issue by polluks** [cc65/cc65#1080] opened 2020-07-09 11:46 UTC
The parallel option does not seem to work. Are our makefiles not smart enough?

**Comment by oliverschmidt** [comment] 2020-07-09 11:59
Sorry but "does not seem to work" doesn't qualify as a valid issue description.

**Comment by polluks** [comment] 2020-07-09 12:15
Well, it's not deterministic
````
...
atarixl - atr10.o
make[1]: *** [atarixl] Error 2
apple2enh - tgi/tgi_load.s
apple2enh - tgi/tgi_load_vectorfont.c
apple2enh - tgi/tgi_outcode.s
apple2enh - tgi/tgi_outtext.s
make[2]: *** Waiting for unfinished jobs....
apple2enh - tgi/tgi_outtextxy.s
apple2enh - tgi/tgi_pieslice.c
apple2enh - tgi/tgi_popxy.s
apple2enh - tgi/tgi_popxy2.s
apple2enh - tgi/tgi_setaspectratio.s
apple2enh - tgi/tgi_setcolor.s
apple2enh - tgi/tgi_setdrawpage.s
apple2enh - tgi/tgi_setpalette.s
apple2enh - tgi/tgi_setpixel.s
apple2enh - tgi/tgi_settextdir.s
apple2enh - tgi/tgi_settextstyle.s
apple2enh - tgi/tgi_setviewpage.s
apple2enh - apple2/tgi_stat_stddrv.s
make[1]: *** [atari] Error 2
apple2enh - apple2/tgi_stddrv.s
...
````
````
GNU Make 3.81
Copyright (C) 2006  Free Software Foundation, Inc.
This is free software; see the source for copying conditions.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE.

This program built for powerpc-apple-darwin9.0
````

**Comment by mrdudz** [comment] 2020-07-09 12:24
I can reproduce it, it randomly fails with -j

To me it looks like the ar65 command comes before all required objects have been compiled (which fails, of course)

**Comment by polluks** [comment] 2020-07-09 12:25
I was reading https://bugzilla.redhat.com/show_bug.cgi?id=212111 but it still fails
````
...
gmake[1]: *** [Makefile:118: atari] Error 2
c64 - c64-georam.o
c64 - c64-hitjoy.o
c64 - c64-numpad.o
c64 - c64-ptvjoy.o
c64 - c64-stdjoy.o
c64 - c64-joy.o
c64 - c64-swlink.o
c64 - c64-hi.o
gmake: *** [Makefile:7: all] Error 2
````
````
GNU Make 4.2.1
Built for powerpc-apple-darwin9.8.0
Copyright (C) 1988-2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
````

**Comment by jmr** [comment] 2020-07-09 12:56
On the broader `make -j` topic, but maybe not related to what you're seeing:

I have a few PRs related to `make -j` that aren't ready to send yet.

What I noticed was:
* the test makefile disables `-j` with `.NOTPARALLEL`
* `cl65` uses essentially `$( basename input.c .c ).s` for the temporary files, so it's not safe to run on the same input, even with different output files.

**Comment by oliverschmidt** [comment] 2020-07-09 15:00
Problems with make -j usually fall into one of the two categories:
1. Incomplete dependencies. I've invested quite some effort to not have that issue. E.g. everything is (supposed to be) dependent from the directory it is writing to.
2. Trashing of "invisible" temporary files.

> To me it looks like the ar65 command comes before all required objects have been compiled (which fails, of course)

I must admit that I would be VERY surprised if that were the issue. Check out https://github.com/cc65/cc65/blob/master/libsrc/Makefile#L289-L290. As one would expect ar65 works exactly with its dependencies. So if it adds a certain file to an archive then this implies that it depends on this file. And that means that make needs to assert that this file is up-to-date beforehand, no matter how.

**Comment by greg-king5** [comment] 2020-07-09 15:26
I cannot reproduce the problem.  What command-line do you use; and, from which directory?

**Comment by mrdudz** [comment] 2020-07-09 15:45
make -j in the root of the sourcetree. if that doesnt trigger it for you, try sth like make -j 5 or so. now that i do it again, it fails differently again. it seems really pretty random.

here are the last "few" lines of output of make -d -j https://pastebin.com/EXg9F6Tp ... i cant figure out WHY it fails at all :(

**Comment by mrdudz** [comment] 2020-07-09 15:53
Update: apparently it needs an excessively high number of processes.... it works for me for any number smaller than 20. so -j 19 works, -j 20 breaks (i have old i5 with 4 cores). really weird

**Comment by jmr** [comment] 2020-07-09 19:18
I'm able to reproduce, even with `-j 19`. It was working with `-j 5`, which is what I normally use.

Here's the error, after I added the filename:
```
ar65: Error: Problem deleting temporary library file '../lib/apple2enh.lib.temp': No such file or directory
```

So something tempfile-related. It looks like it may be trying to make `../lib/apple2enh.lib` twice.

**Comment by greg-king5** [comment] 2020-07-10 01:50
Bad news:  It isn't our fault.  We can't fix it.

The make program seems to have severe memory leakage.  It seems to gobble memory until there is too little left in the system.
Then ...
Some commands can't be run.  Others fail because they can't allocate enough space.  Sub-processes and sub-makes crash.  But, the top-level make command already has started so many jobs that it takes a while to finish running.

**Comment by acqn** [comment] 2020-07-10 07:34
Could we fix test/asm? It seems to be the temporary file 'cpudetect.o' that causes errors with -j.

**Comment by jmr** [comment] 2020-07-10 08:50
> Could we fix test/asm? It seems to be the temporary file 'cpudetect.o' that causes errors with -j.

I'm also seeing problems in other places, but fixing that would be a start.

**Comment by jmr** [comment] 2020-07-10 09:55
@acqn see #1082 ; actually fixing it is next, but at least `make -j` should work from `test/asm/` after that is merged.

**Comment by oliverschmidt** [comment] 2020-07-10 11:09
Merged https://github.com/cc65/cc65/pull/1082.

**Comment by acqn** [comment] 2020-07-10 14:58
> 
> 
> @acqn see #1082 ; actually fixing it is next, but at least `make -j` should work from `test/asm/` after that is merged.

Great! It's now working as expected. Thanks!

**Comment by acqn** [comment] 2020-07-29 09:08
Hmm, while `.NOTPARALLEL` avoids the errors, it makes the tests in test/val too slow. But even that I have moved the `.NOTPARALLEL` away from test/val so I could use `-j`, it has still become impractical for me to check PRs with the testsuit everytime I modify something, as the testsuit is getting larger and larger.... Not to mention to rebuild the libs. I guess I'll rely on the CI from now on.

**Comment by jmr** [comment] 2020-07-29 09:30
> But even that I have moved the .NOTPARALLEL away from test/val so I could use -j

That will almost certainly fail sooner or later. I guess you can retry without `-j` to see if it's a real failure or not.

I have a fix for the `cl65` temp file problems. I was going to polish it a bit, but I'll just try to get a minimal PR instead.

**Comment by oliverschmidt** [comment] 2020-07-29 09:32
> I was going to polish it a bit, but I'll just try to get a minimal PR instead.

I'm not sure if I'm happy about that...

**Comment by jmr** [comment] 2020-07-29 09:43
It's probably better to see the PR before becoming unhappy.

The problem is that the only really portable way to generate a temp file is `tmpnam`, which is deprecated. Windows doesn't support `mkstemp` or `mkstemps`. Are you ok with `tmpnam`?

**Comment by jmr** [comment] 2020-07-29 09:49
> it has still become impractical for me to check PRs with the testsuit everytime I modify something

A good way to speed this up might be to try reducing the number of `$(OPTIONS)`. Start with `g`, then add `O` when that's working, then try all.

**Comment by oliverschmidt** [comment] 2020-07-29 09:51
> It's probably better to see the PR before becoming unhappy.

When instead of something "polished" is replaced with something "minimal" then it seems appropriate to be _**unsure**_, isn't it?

**Comment by oliverschmidt** [comment] 2020-07-30 13:58
> Are you ok with tmpnam?

Yes, however without having seen the code you have in mind I see conceptual issues:

One problem are the .s files created by the compiler and given to the assembler. If the file names aren't the name of the .c files with changed file extension anymore then potential label files generated by the assembler don't show a reasonable header anymore, e.g.:

```
ca65 V2.18 - Git c53b1673
Main file   : xxx.s
Current file: xxx.s
```

One problem are are the .o files created by the assembler and given to the linker. If the file name isn't the name of the .s file with changed file extension anymore then a potential map file generated by the linker doesn't show a reasonable module anymore, e.g.:

```
xxx.o:
    CODE              Offs=000000  Size=000249  Align=00001  Fill=0000
[...]
_main (xxx.o):
    callmain.o                runtime/callmain.s(11)
```

cl65 might be used to only compile and assemble one or several .c files without linking them. In that scenario the .o files are no temporary files. I'm not sure if by the time the assembler is called cl65 has already determined if linking is desired.

**Comment by oliverschmidt** [comment] 2020-07-30 17:36
> I guess I'll rely on the CI from now on.

Okay, so I won't consider CI failures in PR from you as something to comment on anymore. Rather I'll consider them part of your workflow presuming that you'll notice them and take care of them in a subsequent commit.

**Comment by greg-king5** [comment] 2020-08-02 13:44
> The problem is that the only really portable way to generate a temp file is `tmpnam()`, which is deprecated. Windows doesn't support `mkstemp()` or `mkstemps()`. Are you OK with `tmpnam()`?

That isn't the fix that we want.  As Oliver said, they aren't "temporary" files; they're "intermediate" files.  The only fix for cl65 that we want is an option that says where to put those intermediate files.

---
Anyway ... the better way to do parallel tests is to run the base tools directly -- using a separate rule for each tool.  That way, make can decide when to run each tool for each file (cl65 can't do that).  Each rule will create the proper path-name for each input/output file and each optimizer level -- no name clashes.

**Comment by jmr** [comment] 2020-08-02 20:54
> > The problem is that the only really portable way to generate a temp file is `tmpnam()`, which is deprecated. Windows doesn't support `mkstemp()` or `mkstemps()`. Are you OK with `tmpnam()`?
> 
> That isn't the fix that we want. As Oliver said, they aren't "temporary" files; they're "intermediate" files. The only fix for cl65 that we want is an option that says where to put those intermediate files.

If I do `cl65 -o foo.prg foo.c`, then all I care about is `foo.prg`. If there are flags to enable label or map files, then I agree this changes.
 
> Anyway ... the better way to do parallel tests is to run the base tools directly -- using a separate rule for each tool. That way, make can decide when to run each tool for each file (cl65 can't do that). Each rule will create the proper path-name for each input/output file and each optimizer level -- no name clashes.

That's a lot of extra work put on every user. You don't expect `cc -o foo foo.c & cc -o bar foo.c` to fail due to files stomping each other, do you? You also don't have to break this down into separate cpp, cc, as, ld invocations if you don't want to.

**Comment by oliverschmidt** [comment] 2020-08-02 21:17
From my POV this discussion is starting to go off the rails.

I'm not going to merge a PR that breaks things by introducing randomly named files.

> That's a lot of extra work put on every user [...]

The average user doesn't build several variants of the same source files in parallel ;-)

And apart from that cl65 has other conceptual limits e.g. creating dependency files. Every serious user calls the tools in question individually.

**Closed** 2020-08-26 18:40 UTC
Labels: bug

**Comment by oliverschmidt** [comment] 2021-02-17 10:39
After all this issue turns out to have several facets.

One facet was indeed fixed with https://github.com/cc65/cc65/commit/c658acbf850e32508ea0e14f0f62d675a009c7d9.

Another facet is fixed now with https://github.com/cc65/cc65/commit/3a7282544e0a818bf8fe39970df912a8eb4ed87f.

I'll keep this issue closed until we know if there are more facets left...
